# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hub/v1/envelope.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hub/v1/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15hub/v1/envelope.proto\x12\x06hub.v1\x1a\x19google/protobuf/any.proto\"h\n\x07Subject\x12!\n\x04kind\x18\x01 \x01(\x0e\x32\x13.hub.v1.SubjectKind\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0e\n\x06tenant\x18\x03 \x01(\t\x12\x0e\n\x06scopes\x18\x04 \x03(\t\x12\x0e\n\x06origin\x18\x05 \x01(\t\"S\n\nPayloadRef\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0e\n\x06sha256\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x04\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\"\x84\x03\n\x08\x45nvelope\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\x0f\n\x07span_id\x18\x03 \x01(\t\x12\x0f\n\x07\x66low_id\x18\x04 \x01(\t\x12\x0e\n\x06run_id\x18\x05 \x01(\t\x12\x0f\n\x07node_id\x18\x06 \x01(\t\x12\x0e\n\x06tenant\x18\x07 \x01(\t\x12 \n\x07subject\x18\x08 \x01(\x0b\x32\x0f.hub.v1.Subject\x12\x13\n\x0b\x64\x65\x61\x64line_ms\x18\t \x01(\x03\x12!\n\x04type\x18\n \x01(\x0e\x32\x13.hub.v1.PayloadType\x12%\n\x07payload\x18\x0b \x01(\x0b\x32\x14.google.protobuf.Any\x12\'\n\x0bpayload_ref\x18\x0c \x01(\x0b\x32\x12.hub.v1.PayloadRef\x12(\n\x04meta\x18\r \x03(\x0b\x32\x1a.hub.v1.Envelope.MetaEntry\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x8d\x01\n\x0bSubjectKind\x12\x1c\n\x18SUBJECT_KIND_UNSPECIFIED\x10\x00\x12\x16\n\x12SUBJECT_KIND_HUMAN\x10\x01\x12\x16\n\x12SUBJECT_KIND_AGENT\x10\x02\x12\x17\n\x13SUBJECT_KIND_PLUGIN\x10\x03\x12\x17\n\x13SUBJECT_KIND_SYSTEM\x10\x04*\x90\x01\n\x0bPayloadType\x12\x1c\n\x18PAYLOAD_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14PAYLOAD_TYPE_REQUEST\x10\x01\x12\x16\n\x12PAYLOAD_TYPE_EVENT\x10\x02\x12\x18\n\x14PAYLOAD_TYPE_COMMAND\x10\x03\x12\x17\n\x13PAYLOAD_TYPE_RESULT\x10\x04\x42;Z9github.com/mahingbun-dev/anc-hub/sdk/go/proto/hubv1;hubv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub.v1.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/mahingbun-dev/anc-hub/sdk/go/proto/hubv1;hubv1'
  _globals['_ENVELOPE_METAENTRY']._loaded_options = None
  _globals['_ENVELOPE_METAENTRY']._serialized_options = b'8\001'
  _globals['_SUBJECTKIND']._serialized_start=643
  _globals['_SUBJECTKIND']._serialized_end=784
  _globals['_PAYLOADTYPE']._serialized_start=787
  _globals['_PAYLOADTYPE']._serialized_end=931
  _globals['_SUBJECT']._serialized_start=60
  _globals['_SUBJECT']._serialized_end=164
  _globals['_PAYLOADREF']._serialized_start=166
  _globals['_PAYLOADREF']._serialized_end=249
  _globals['_ENVELOPE']._serialized_start=252
  _globals['_ENVELOPE']._serialized_end=640
  _globals['_ENVELOPE_METAENTRY']._serialized_start=597
  _globals['_ENVELOPE_METAENTRY']._serialized_end=640
# @@protoc_insertion_point(module_scope)
