# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hubkit.proto.hubv1 import gateway_pb2 as hub_dot_v1_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hub/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginGatewayStub:
    """插件 → 中台：发现与互调。

    插件之间不直连：直连会绕过中台的治理、审计、熔断与身份体系，与中台定位冲突。
    同步互调一律经中台代调（A→hub→B），下游复用与 flow 执行同一条
    Invoker / Governor / 审计全链路；发现能力（清单 / 消息端点 / 契约）也只从中台取。

    与 Publish（异步触发 flow，拿不到结果）的分工：需要下游处理结果的同步场景走 Invoke。

    **身份与 Publish 同强度**：每个 RPC 都凭 metadata `x-hub-state-token` 反查调用方
    插件身份，subject 由中台无条件覆盖为调用方——请求信封里自报的 subject 不可信。

    **结果语义**：业务层结果（下游拒绝、未授权、超限、成环…）一律走响应字段
    （outcome + reason / issues），只有基础设施故障（未鉴权、下游不可达、内部错误）
    才返回 gRPC Status——SDK 据此抛类型化异常，调用方不必解析错误字符串。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPlugins = channel.unary_unary(
                '/hub.v1.PluginGateway/ListPlugins',
                request_serializer=hub_dot_v1_dot_gateway__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_gateway__pb2.ListPluginsResponse.FromString,
                _registered_method=True)
        self.DescribeMessage = channel.unary_unary(
                '/hub.v1.PluginGateway/DescribeMessage',
                request_serializer=hub_dot_v1_dot_gateway__pb2.DescribeMessageRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_gateway__pb2.DescribeMessageResponse.FromString,
                _registered_method=True)
        self.GetContract = channel.unary_unary(
                '/hub.v1.PluginGateway/GetContract',
                request_serializer=hub_dot_v1_dot_gateway__pb2.GetContractRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_gateway__pb2.GetContractResponse.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/hub.v1.PluginGateway/Invoke',
                request_serializer=hub_dot_v1_dot_gateway__pb2.InvokeRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_gateway__pb2.InvokeResponse.FromString,
                _registered_method=True)


class PluginGatewayServicer:
    """插件 → 中台：发现与互调。

    插件之间不直连：直连会绕过中台的治理、审计、熔断与身份体系，与中台定位冲突。
    同步互调一律经中台代调（A→hub→B），下游复用与 flow 执行同一条
    Invoker / Governor / 审计全链路；发现能力（清单 / 消息端点 / 契约）也只从中台取。

    与 Publish（异步触发 flow，拿不到结果）的分工：需要下游处理结果的同步场景走 Invoke。

    **身份与 Publish 同强度**：每个 RPC 都凭 metadata `x-hub-state-token` 反查调用方
    插件身份，subject 由中台无条件覆盖为调用方——请求信封里自报的 subject 不可信。

    **结果语义**：业务层结果（下游拒绝、未授权、超限、成环…）一律走响应字段
    （outcome + reason / issues），只有基础设施故障（未鉴权、下游不可达、内部错误）
    才返回 gRPC Status——SDK 据此抛类型化异常，调用方不必解析错误字符串。
    """

    def ListPlugins(self, request, context):
        """在线插件清单。插件用它找「能调谁」，不必旁路维护硬编码名单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeMessage(self, request, context):
        """消息类型 → 生产者 / 消费者。按消息反查上下游，发现可订阅或可调用的数据流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContract(self, request, context):
        """插件契约 + 字段级 schema。调别人之前先看它吃什么、吐什么
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """同步互调 A→hub→B。中台负责鉴权、配额、防环、subject 覆盖与 deadline 夹紧
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=hub_dot_v1_dot_gateway__pb2.ListPluginsRequest.FromString,
                    response_serializer=hub_dot_v1_dot_gateway__pb2.ListPluginsResponse.SerializeToString,
            ),
            'DescribeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeMessage,
                    request_deserializer=hub_dot_v1_dot_gateway__pb2.DescribeMessageRequest.FromString,
                    response_serializer=hub_dot_v1_dot_gateway__pb2.DescribeMessageResponse.SerializeToString,
            ),
            'GetContract': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContract,
                    request_deserializer=hub_dot_v1_dot_gateway__pb2.GetContractRequest.FromString,
                    response_serializer=hub_dot_v1_dot_gateway__pb2.GetContractResponse.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=hub_dot_v1_dot_gateway__pb2.InvokeRequest.FromString,
                    response_serializer=hub_dot_v1_dot_gateway__pb2.InvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.PluginGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.PluginGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginGateway:
    """插件 → 中台：发现与互调。

    插件之间不直连：直连会绕过中台的治理、审计、熔断与身份体系，与中台定位冲突。
    同步互调一律经中台代调（A→hub→B），下游复用与 flow 执行同一条
    Invoker / Governor / 审计全链路；发现能力（清单 / 消息端点 / 契约）也只从中台取。

    与 Publish（异步触发 flow，拿不到结果）的分工：需要下游处理结果的同步场景走 Invoke。

    **身份与 Publish 同强度**：每个 RPC 都凭 metadata `x-hub-state-token` 反查调用方
    插件身份，subject 由中台无条件覆盖为调用方——请求信封里自报的 subject 不可信。

    **结果语义**：业务层结果（下游拒绝、未授权、超限、成环…）一律走响应字段
    （outcome + reason / issues），只有基础设施故障（未鉴权、下游不可达、内部错误）
    才返回 gRPC Status——SDK 据此抛类型化异常，调用方不必解析错误字符串。
    """

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginGateway/ListPlugins',
            hub_dot_v1_dot_gateway__pb2.ListPluginsRequest.SerializeToString,
            hub_dot_v1_dot_gateway__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginGateway/DescribeMessage',
            hub_dot_v1_dot_gateway__pb2.DescribeMessageRequest.SerializeToString,
            hub_dot_v1_dot_gateway__pb2.DescribeMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginGateway/GetContract',
            hub_dot_v1_dot_gateway__pb2.GetContractRequest.SerializeToString,
            hub_dot_v1_dot_gateway__pb2.GetContractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginGateway/Invoke',
            hub_dot_v1_dot_gateway__pb2.InvokeRequest.SerializeToString,
            hub_dot_v1_dot_gateway__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
