# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hubkit.proto.hubv1 import plugin_pb2 as hub_dot_v1_dot_plugin__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hub/v1/plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginRuntimeStub:
    """中台 → 插件。

    每个插件必须实现全部方法，缺一不可：
    - Validate 是「数据校验规则」，数据进来先过它，通过后才进 Handle
    - Handle 是「插件体」，自主实现的数据输入输出
    二者同版本发布，规则与实现不可能漂移。

    中台按插件自注册时上报的 advertise 地址直连，不要求与中台同机。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/hub.v1.PluginRuntime/Describe',
                request_serializer=hub_dot_v1_dot_plugin__pb2.DescribeRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_plugin__pb2.PluginManifest.FromString,
                _registered_method=True)
        self.Validate = channel.unary_unary(
                '/hub.v1.PluginRuntime/Validate',
                request_serializer=hub_dot_v1_dot_plugin__pb2.ValidateRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_plugin__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.Handle = channel.unary_unary(
                '/hub.v1.PluginRuntime/Handle',
                request_serializer=hub_dot_v1_dot_plugin__pb2.HandleRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_plugin__pb2.HandleResponse.FromString,
                _registered_method=True)
        self.HandleStream = channel.unary_stream(
                '/hub.v1.PluginRuntime/HandleStream',
                request_serializer=hub_dot_v1_dot_plugin__pb2.HandleRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_plugin__pb2.HandleResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/hub.v1.PluginRuntime/Health',
                request_serializer=hub_dot_v1_dot_plugin__pb2.HealthRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_plugin__pb2.HealthResponse.FromString,
                _registered_method=True)


class PluginRuntimeServicer:
    """中台 → 插件。

    每个插件必须实现全部方法，缺一不可：
    - Validate 是「数据校验规则」，数据进来先过它，通过后才进 Handle
    - Handle 是「插件体」，自主实现的数据输入输出
    二者同版本发布，规则与实现不可能漂移。

    中台按插件自注册时上报的 advertise 地址直连，不要求与中台同机。
    """

    def Describe(self, request, context):
        """拉取 manifest。中台用它核对插件自述与注册时提交的内容是否一致。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """校验器。校验失败按 manifest 的 validation 策略处理（默认拒绝）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Handle(self, request, context):
        """插件体。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleStream(self, request, context):
        """逐条结果的流式版本（大报文 / 多条输出）。中台侧走 server-streaming 转发。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """健康探测。中台在注册时与心跳周期内调用。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=hub_dot_v1_dot_plugin__pb2.DescribeRequest.FromString,
                    response_serializer=hub_dot_v1_dot_plugin__pb2.PluginManifest.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=hub_dot_v1_dot_plugin__pb2.ValidateRequest.FromString,
                    response_serializer=hub_dot_v1_dot_plugin__pb2.ValidateResponse.SerializeToString,
            ),
            'Handle': grpc.unary_unary_rpc_method_handler(
                    servicer.Handle,
                    request_deserializer=hub_dot_v1_dot_plugin__pb2.HandleRequest.FromString,
                    response_serializer=hub_dot_v1_dot_plugin__pb2.HandleResponse.SerializeToString,
            ),
            'HandleStream': grpc.unary_stream_rpc_method_handler(
                    servicer.HandleStream,
                    request_deserializer=hub_dot_v1_dot_plugin__pb2.HandleRequest.FromString,
                    response_serializer=hub_dot_v1_dot_plugin__pb2.HandleResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=hub_dot_v1_dot_plugin__pb2.HealthRequest.FromString,
                    response_serializer=hub_dot_v1_dot_plugin__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.PluginRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.PluginRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginRuntime:
    """中台 → 插件。

    每个插件必须实现全部方法，缺一不可：
    - Validate 是「数据校验规则」，数据进来先过它，通过后才进 Handle
    - Handle 是「插件体」，自主实现的数据输入输出
    二者同版本发布，规则与实现不可能漂移。

    中台按插件自注册时上报的 advertise 地址直连，不要求与中台同机。
    """

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginRuntime/Describe',
            hub_dot_v1_dot_plugin__pb2.DescribeRequest.SerializeToString,
            hub_dot_v1_dot_plugin__pb2.PluginManifest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginRuntime/Validate',
            hub_dot_v1_dot_plugin__pb2.ValidateRequest.SerializeToString,
            hub_dot_v1_dot_plugin__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Handle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginRuntime/Handle',
            hub_dot_v1_dot_plugin__pb2.HandleRequest.SerializeToString,
            hub_dot_v1_dot_plugin__pb2.HandleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hub.v1.PluginRuntime/HandleStream',
            hub_dot_v1_dot_plugin__pb2.HandleRequest.SerializeToString,
            hub_dot_v1_dot_plugin__pb2.HandleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginRuntime/Health',
            hub_dot_v1_dot_plugin__pb2.HealthRequest.SerializeToString,
            hub_dot_v1_dot_plugin__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
