# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hubkit.proto.hubv1 import registry_pb2 as hub_dot_v1_dot_registry__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hub/v1/registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginRegistryStub:
    """插件 → 中台。

    插件是独立的进程/容器，可能部署在任何主机上，因此这条链路要经 nginx 的
    grpc_pass 独立端口进来（见 docs/design.md 的网络拓扑）。

    心跳刻意用定时 unary 而非长连接 stream：避开 gRPC 经 nginx 的保活与超时坑。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/hub.v1.PluginRegistry/Register',
                request_serializer=hub_dot_v1_dot_registry__pb2.RegisterRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_registry__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/hub.v1.PluginRegistry/Heartbeat',
                request_serializer=hub_dot_v1_dot_registry__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_registry__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/hub.v1.PluginRegistry/Unregister',
                request_serializer=hub_dot_v1_dot_registry__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_registry__pb2.UnregisterResponse.FromString,
                _registered_method=True)


class PluginRegistryServicer:
    """插件 → 中台。

    插件是独立的进程/容器，可能部署在任何主机上，因此这条链路要经 nginx 的
    grpc_pass 独立端口进来（见 docs/design.md 的网络拓扑）。

    心跳刻意用定时 unary 而非长连接 stream：避开 gRPC 经 nginx 的保活与超时坑。
    """

    def Register(self, request, context):
        """自注册。中台收到后会做三件事，任一不通过即拒绝：
        1. 可达性探测（试连 advertise_addr 并调 Health）
        2. descriptor 解析与字段级兼容检查
        3. MCP 工具名冲突检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """优雅退出时主动摘除；未调用则由心跳超时兜底。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=hub_dot_v1_dot_registry__pb2.RegisterRequest.FromString,
                    response_serializer=hub_dot_v1_dot_registry__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=hub_dot_v1_dot_registry__pb2.HeartbeatRequest.FromString,
                    response_serializer=hub_dot_v1_dot_registry__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=hub_dot_v1_dot_registry__pb2.UnregisterRequest.FromString,
                    response_serializer=hub_dot_v1_dot_registry__pb2.UnregisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.PluginRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.PluginRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginRegistry:
    """插件 → 中台。

    插件是独立的进程/容器，可能部署在任何主机上，因此这条链路要经 nginx 的
    grpc_pass 独立端口进来（见 docs/design.md 的网络拓扑）。

    心跳刻意用定时 unary 而非长连接 stream：避开 gRPC 经 nginx 的保活与超时坑。
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginRegistry/Register',
            hub_dot_v1_dot_registry__pb2.RegisterRequest.SerializeToString,
            hub_dot_v1_dot_registry__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginRegistry/Heartbeat',
            hub_dot_v1_dot_registry__pb2.HeartbeatRequest.SerializeToString,
            hub_dot_v1_dot_registry__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.PluginRegistry/Unregister',
            hub_dot_v1_dot_registry__pb2.UnregisterRequest.SerializeToString,
            hub_dot_v1_dot_registry__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
