# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hub/v1/state.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hub/v1/state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hubkit.proto.hubv1 import envelope_pb2 as hub_dot_v1_dot_envelope__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12hub/v1/state.proto\x12\x06hub.v1\x1a\x15hub/v1/envelope.proto\"\'\n\x05KvKey\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"*\n\x0cKvGetRequest\x12\x1a\n\x03key\x18\x01 \x01(\x0b\x32\r.hub.v1.KvKey\"-\n\rKvGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\"N\n\x0cKvPutRequest\x12\x1a\n\x03key\x18\x01 \x01(\x0b\x32\r.hub.v1.KvKey\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x13\n\x0bttl_seconds\x18\x03 \x01(\x03\"\x0f\n\rKvPutResponse\"-\n\x0fKvDeleteRequest\x12\x1a\n\x03key\x18\x01 \x01(\x0b\x32\r.hub.v1.KvKey\"#\n\x10KvDeleteResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\"A\n\rKvScanRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\r\"2\n\x0eKvScanResponse\x12 \n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0f.hub.v1.KvEntry\"%\n\x07KvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"D\n\x0ePublishRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\"\n\x08\x65nvelope\x18\x02 \x01(\x0b\x32\x10.hub.v1.Envelope\"C\n\x0fPublishResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t2\xaa\x02\n\x08HubState\x12\x34\n\x05KvGet\x12\x14.hub.v1.KvGetRequest\x1a\x15.hub.v1.KvGetResponse\x12\x34\n\x05KvPut\x12\x14.hub.v1.KvPutRequest\x1a\x15.hub.v1.KvPutResponse\x12=\n\x08KvDelete\x12\x17.hub.v1.KvDeleteRequest\x1a\x18.hub.v1.KvDeleteResponse\x12\x37\n\x06KvScan\x12\x15.hub.v1.KvScanRequest\x1a\x16.hub.v1.KvScanResponse\x12:\n\x07Publish\x12\x16.hub.v1.PublishRequest\x1a\x17.hub.v1.PublishResponseB>Z<github.com/mahingbun-dev/plugin-hub/sdk/go/proto/hubv1;hubv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub.v1.state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/mahingbun-dev/plugin-hub/sdk/go/proto/hubv1;hubv1'
  _globals['_KVKEY']._serialized_start=53
  _globals['_KVKEY']._serialized_end=92
  _globals['_KVGETREQUEST']._serialized_start=94
  _globals['_KVGETREQUEST']._serialized_end=136
  _globals['_KVGETRESPONSE']._serialized_start=138
  _globals['_KVGETRESPONSE']._serialized_end=183
  _globals['_KVPUTREQUEST']._serialized_start=185
  _globals['_KVPUTREQUEST']._serialized_end=263
  _globals['_KVPUTRESPONSE']._serialized_start=265
  _globals['_KVPUTRESPONSE']._serialized_end=280
  _globals['_KVDELETEREQUEST']._serialized_start=282
  _globals['_KVDELETEREQUEST']._serialized_end=327
  _globals['_KVDELETERESPONSE']._serialized_start=329
  _globals['_KVDELETERESPONSE']._serialized_end=364
  _globals['_KVSCANREQUEST']._serialized_start=366
  _globals['_KVSCANREQUEST']._serialized_end=431
  _globals['_KVSCANRESPONSE']._serialized_start=433
  _globals['_KVSCANRESPONSE']._serialized_end=483
  _globals['_KVENTRY']._serialized_start=485
  _globals['_KVENTRY']._serialized_end=522
  _globals['_PUBLISHREQUEST']._serialized_start=524
  _globals['_PUBLISHREQUEST']._serialized_end=592
  _globals['_PUBLISHRESPONSE']._serialized_start=594
  _globals['_PUBLISHRESPONSE']._serialized_end=661
  _globals['_HUBSTATE']._serialized_start=664
  _globals['_HUBSTATE']._serialized_end=962
# @@protoc_insertion_point(module_scope)
