# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hubkit.proto.hubv1 import state_pb2 as hub_dot_v1_dot_state__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hub/v1/state_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HubStateStub:
    """插件 → 中台：外置状态 API。

    插件被**强制无状态**——实例内存不保证跨调用保留，因此热切换零代价、
    水平扩展无障碍、重放与测试都简单。所有需要跨调用保留的东西都走这里。

    中台按**注册时下发的凭证**反查插件名并强制加前缀 `hub:state:{插件名}:`——前缀取自
    凭证而非插件自报的字段，插件自报的 namespace 只作为子空间拼在后面。

    **但这不是插件间的隔离承诺**：凭证只证明注册方自称是某个插件名、并通过了该名字的
    注册校验，不证明它就是那个插件。插件面按设计不鉴权，任何能连上该端口的进程都能注册
    一个与目标插件契约兼容的新版本、拿到反查为该插件的凭证并读写它的状态空间。
    隔离强度与完整边界见 `docs/design.md` 风险 11。

    **租户维度本期未实现**：HubState 请求只有 KvKey，没有 Envelope 上下文，
    协议上推导不出"当前租户"，而插件自报的租户不可信。多租户需求出现时再单独设计。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.KvGet = channel.unary_unary(
                '/hub.v1.HubState/KvGet',
                request_serializer=hub_dot_v1_dot_state__pb2.KvGetRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_state__pb2.KvGetResponse.FromString,
                _registered_method=True)
        self.KvPut = channel.unary_unary(
                '/hub.v1.HubState/KvPut',
                request_serializer=hub_dot_v1_dot_state__pb2.KvPutRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_state__pb2.KvPutResponse.FromString,
                _registered_method=True)
        self.KvDelete = channel.unary_unary(
                '/hub.v1.HubState/KvDelete',
                request_serializer=hub_dot_v1_dot_state__pb2.KvDeleteRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_state__pb2.KvDeleteResponse.FromString,
                _registered_method=True)
        self.KvScan = channel.unary_unary(
                '/hub.v1.HubState/KvScan',
                request_serializer=hub_dot_v1_dot_state__pb2.KvScanRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_state__pb2.KvScanResponse.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/hub.v1.HubState/Publish',
                request_serializer=hub_dot_v1_dot_state__pb2.PublishRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_state__pb2.PublishResponse.FromString,
                _registered_method=True)


class HubStateServicer:
    """插件 → 中台：外置状态 API。

    插件被**强制无状态**——实例内存不保证跨调用保留，因此热切换零代价、
    水平扩展无障碍、重放与测试都简单。所有需要跨调用保留的东西都走这里。

    中台按**注册时下发的凭证**反查插件名并强制加前缀 `hub:state:{插件名}:`——前缀取自
    凭证而非插件自报的字段，插件自报的 namespace 只作为子空间拼在后面。

    **但这不是插件间的隔离承诺**：凭证只证明注册方自称是某个插件名、并通过了该名字的
    注册校验，不证明它就是那个插件。插件面按设计不鉴权，任何能连上该端口的进程都能注册
    一个与目标插件契约兼容的新版本、拿到反查为该插件的凭证并读写它的状态空间。
    隔离强度与完整边界见 `docs/design.md` 风险 11。

    **租户维度本期未实现**：HubState 请求只有 KvKey，没有 Envelope 上下文，
    协议上推导不出"当前租户"，而插件自报的租户不可信。多租户需求出现时再单独设计。
    """

    def KvGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KvPut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KvDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KvScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """触发下游：把一条 Envelope 投给目标 flow。
        中台负责防环与限流，防止插件互相触发形成风暴。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HubStateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'KvGet': grpc.unary_unary_rpc_method_handler(
                    servicer.KvGet,
                    request_deserializer=hub_dot_v1_dot_state__pb2.KvGetRequest.FromString,
                    response_serializer=hub_dot_v1_dot_state__pb2.KvGetResponse.SerializeToString,
            ),
            'KvPut': grpc.unary_unary_rpc_method_handler(
                    servicer.KvPut,
                    request_deserializer=hub_dot_v1_dot_state__pb2.KvPutRequest.FromString,
                    response_serializer=hub_dot_v1_dot_state__pb2.KvPutResponse.SerializeToString,
            ),
            'KvDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.KvDelete,
                    request_deserializer=hub_dot_v1_dot_state__pb2.KvDeleteRequest.FromString,
                    response_serializer=hub_dot_v1_dot_state__pb2.KvDeleteResponse.SerializeToString,
            ),
            'KvScan': grpc.unary_unary_rpc_method_handler(
                    servicer.KvScan,
                    request_deserializer=hub_dot_v1_dot_state__pb2.KvScanRequest.FromString,
                    response_serializer=hub_dot_v1_dot_state__pb2.KvScanResponse.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=hub_dot_v1_dot_state__pb2.PublishRequest.FromString,
                    response_serializer=hub_dot_v1_dot_state__pb2.PublishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.HubState', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.HubState', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HubState:
    """插件 → 中台：外置状态 API。

    插件被**强制无状态**——实例内存不保证跨调用保留，因此热切换零代价、
    水平扩展无障碍、重放与测试都简单。所有需要跨调用保留的东西都走这里。

    中台按**注册时下发的凭证**反查插件名并强制加前缀 `hub:state:{插件名}:`——前缀取自
    凭证而非插件自报的字段，插件自报的 namespace 只作为子空间拼在后面。

    **但这不是插件间的隔离承诺**：凭证只证明注册方自称是某个插件名、并通过了该名字的
    注册校验，不证明它就是那个插件。插件面按设计不鉴权，任何能连上该端口的进程都能注册
    一个与目标插件契约兼容的新版本、拿到反查为该插件的凭证并读写它的状态空间。
    隔离强度与完整边界见 `docs/design.md` 风险 11。

    **租户维度本期未实现**：HubState 请求只有 KvKey，没有 Envelope 上下文，
    协议上推导不出"当前租户"，而插件自报的租户不可信。多租户需求出现时再单独设计。
    """

    @staticmethod
    def KvGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.HubState/KvGet',
            hub_dot_v1_dot_state__pb2.KvGetRequest.SerializeToString,
            hub_dot_v1_dot_state__pb2.KvGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KvPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.HubState/KvPut',
            hub_dot_v1_dot_state__pb2.KvPutRequest.SerializeToString,
            hub_dot_v1_dot_state__pb2.KvPutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KvDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.HubState/KvDelete',
            hub_dot_v1_dot_state__pb2.KvDeleteRequest.SerializeToString,
            hub_dot_v1_dot_state__pb2.KvDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KvScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.HubState/KvScan',
            hub_dot_v1_dot_state__pb2.KvScanRequest.SerializeToString,
            hub_dot_v1_dot_state__pb2.KvScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.HubState/Publish',
            hub_dot_v1_dot_state__pb2.PublishRequest.SerializeToString,
            hub_dot_v1_dot_state__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
