// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: hub/v1/envelope.proto

package hubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubjectKind int32

const (
	SubjectKind_SUBJECT_KIND_UNSPECIFIED SubjectKind = 0
	SubjectKind_SUBJECT_KIND_HUMAN       SubjectKind = 1
	SubjectKind_SUBJECT_KIND_AGENT       SubjectKind = 2
	SubjectKind_SUBJECT_KIND_PLUGIN      SubjectKind = 3
	SubjectKind_SUBJECT_KIND_SYSTEM      SubjectKind = 4
)

// Enum value maps for SubjectKind.
var (
	SubjectKind_name = map[int32]string{
		0: "SUBJECT_KIND_UNSPECIFIED",
		1: "SUBJECT_KIND_HUMAN",
		2: "SUBJECT_KIND_AGENT",
		3: "SUBJECT_KIND_PLUGIN",
		4: "SUBJECT_KIND_SYSTEM",
	}
	SubjectKind_value = map[string]int32{
		"SUBJECT_KIND_UNSPECIFIED": 0,
		"SUBJECT_KIND_HUMAN":       1,
		"SUBJECT_KIND_AGENT":       2,
		"SUBJECT_KIND_PLUGIN":      3,
		"SUBJECT_KIND_SYSTEM":      4,
	}
)

func (x SubjectKind) Enum() *SubjectKind {
	p := new(SubjectKind)
	*p = x
	return p
}

func (x SubjectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubjectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (SubjectKind) Type() protoreflect.EnumType {
	return &file_hub_v1_envelope_proto_enumTypes[0]
}

func (x SubjectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubjectKind.Descriptor instead.
func (SubjectKind) EnumDescriptor() ([]byte, []int) {
	return file_hub_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// 载荷在数据流中的语义
type PayloadType int32

const (
	PayloadType_PAYLOAD_TYPE_UNSPECIFIED PayloadType = 0
	PayloadType_PAYLOAD_TYPE_REQUEST     PayloadType = 1
	PayloadType_PAYLOAD_TYPE_EVENT       PayloadType = 2
	PayloadType_PAYLOAD_TYPE_COMMAND     PayloadType = 3
	PayloadType_PAYLOAD_TYPE_RESULT      PayloadType = 4
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		0: "PAYLOAD_TYPE_UNSPECIFIED",
		1: "PAYLOAD_TYPE_REQUEST",
		2: "PAYLOAD_TYPE_EVENT",
		3: "PAYLOAD_TYPE_COMMAND",
		4: "PAYLOAD_TYPE_RESULT",
	}
	PayloadType_value = map[string]int32{
		"PAYLOAD_TYPE_UNSPECIFIED": 0,
		"PAYLOAD_TYPE_REQUEST":     1,
		"PAYLOAD_TYPE_EVENT":       2,
		"PAYLOAD_TYPE_COMMAND":     3,
		"PAYLOAD_TYPE_RESULT":      4,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_v1_envelope_proto_enumTypes[1].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_hub_v1_envelope_proto_enumTypes[1]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_hub_v1_envelope_proto_rawDescGZIP(), []int{1}
}

// 调用主体：谁触发了这次数据流。
//
// 管理面与控制面按设计是全插件化的（中台自身不含鉴权逻辑），
// subject 由鉴权插件填充，中台只负责透传、审计与限流。
type Subject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  SubjectKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=hub.v1.SubjectKind" json:"kind,omitempty"`
	// 人类为 userCode；agent 为会话 id；插件为插件名；系统为子系统标识
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Tenant string `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// 权限位，供下游插件做业务级鉴权
	Scopes []string `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// 原始凭证来源的描述。仅透传，不落库。
	Origin        string `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_hub_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_hub_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Subject) GetKind() SubjectKind {
	if x != nil {
		return x.Kind
	}
	return SubjectKind_SUBJECT_KIND_UNSPECIFIED
}

func (x *Subject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subject) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Subject) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *Subject) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

// 超限载荷的引用。
//
// 载荷内联上限 4MB（可配）；超出时改走引用传递，payload 留空、payload_ref 填写。
// 物流场景的大单据与附件走这条路，避免顶爆内存、Redis Stream 与 gRPC 消息上限。
type PayloadRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uri   string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// 内容摘要，用于校验引用内容未被篡改
	Sha256        string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	SizeBytes     uint64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadRef) Reset() {
	*x = PayloadRef{}
	mi := &file_hub_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadRef) ProtoMessage() {}

func (x *PayloadRef) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadRef.ProtoReflect.Descriptor instead.
func (*PayloadRef) Descriptor() ([]byte, []int) {
	return file_hub_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadRef) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *PayloadRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *PayloadRef) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PayloadRef) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ULID，同时作为幂等键来源（总线是 at-least-once，去重靠它）
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// W3C Trace Context
	TraceId string   `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId  string   `protobuf:"bytes,3,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	FlowId  string   `protobuf:"bytes,4,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	RunId   string   `protobuf:"bytes,5,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NodeId  string   `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Tenant  string   `protobuf:"bytes,7,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Subject *Subject `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	// 绝对 deadline（Unix 毫秒）。逐跳递减，插件应据此提前放弃而不是把时间耗光。
	DeadlineMs int64       `protobuf:"varint,9,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	Type       PayloadType `protobuf:"varint,10,opt,name=type,proto3,enum=hub.v1.PayloadType" json:"type,omitempty"`
	// 业务载荷。
	//
	// 契约标识 = type_url 的最后一段（全限定消息名），
	// 例如 `type.googleapis.com/wms.v1.OrderCreated`。
	// 中台在编排时静态校验上下游的全限定名能否对上，运行时校验实际类型是否符合 manifest。
	Payload *anypb.Any `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	// payload 超出内联上限时填此项，此时 payload 必须为空
	PayloadRef    *PayloadRef       `protobuf:"bytes,12,opt,name=payload_ref,json=payloadRef,proto3" json:"payload_ref,omitempty"`
	Meta          map[string]string `protobuf:"bytes,13,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_hub_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_hub_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Envelope) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *Envelope) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Envelope) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Envelope) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Envelope) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Envelope) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *Envelope) GetType() PayloadType {
	if x != nil {
		return x.Type
	}
	return PayloadType_PAYLOAD_TYPE_UNSPECIFIED
}

func (x *Envelope) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetPayloadRef() *PayloadRef {
	if x != nil {
		return x.PayloadRef
	}
	return nil
}

func (x *Envelope) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_hub_v1_envelope_proto protoreflect.FileDescriptor

const file_hub_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x15hub/v1/envelope.proto\x12\x06hub.v1\x1a\x19google/protobuf/any.proto\"\x8a\x01\n" +
	"\aSubject\x12'\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x13.hub.v1.SubjectKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\"x\n" +
	"\n" +
	"PayloadRef\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"\x81\x04\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x03 \x01(\tR\x06spanId\x12\x17\n" +
	"\aflow_id\x18\x04 \x01(\tR\x06flowId\x12\x15\n" +
	"\x06run_id\x18\x05 \x01(\tR\x05runId\x12\x17\n" +
	"\anode_id\x18\x06 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06tenant\x18\a \x01(\tR\x06tenant\x12)\n" +
	"\asubject\x18\b \x01(\v2\x0f.hub.v1.SubjectR\asubject\x12\x1f\n" +
	"\vdeadline_ms\x18\t \x01(\x03R\n" +
	"deadlineMs\x12'\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2\x13.hub.v1.PayloadTypeR\x04type\x12.\n" +
	"\apayload\x18\v \x01(\v2\x14.google.protobuf.AnyR\apayload\x123\n" +
	"\vpayload_ref\x18\f \x01(\v2\x12.hub.v1.PayloadRefR\n" +
	"payloadRef\x12.\n" +
	"\x04meta\x18\r \x03(\v2\x1a.hub.v1.Envelope.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8d\x01\n" +
	"\vSubjectKind\x12\x1c\n" +
	"\x18SUBJECT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SUBJECT_KIND_HUMAN\x10\x01\x12\x16\n" +
	"\x12SUBJECT_KIND_AGENT\x10\x02\x12\x17\n" +
	"\x13SUBJECT_KIND_PLUGIN\x10\x03\x12\x17\n" +
	"\x13SUBJECT_KIND_SYSTEM\x10\x04*\x90\x01\n" +
	"\vPayloadType\x12\x1c\n" +
	"\x18PAYLOAD_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PAYLOAD_TYPE_REQUEST\x10\x01\x12\x16\n" +
	"\x12PAYLOAD_TYPE_EVENT\x10\x02\x12\x18\n" +
	"\x14PAYLOAD_TYPE_COMMAND\x10\x03\x12\x17\n" +
	"\x13PAYLOAD_TYPE_RESULT\x10\x04BIZGgithub.com/mahingbun-dev/anc-hub/sdk/go/proto/hubv1;hubv1b\x06proto3"

var (
	file_hub_v1_envelope_proto_rawDescOnce sync.Once
	file_hub_v1_envelope_proto_rawDescData []byte
)

func file_hub_v1_envelope_proto_rawDescGZIP() []byte {
	file_hub_v1_envelope_proto_rawDescOnce.Do(func() {
		file_hub_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_v1_envelope_proto_rawDesc), len(file_hub_v1_envelope_proto_rawDesc)))
	})
	return file_hub_v1_envelope_proto_rawDescData
}

var file_hub_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hub_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hub_v1_envelope_proto_goTypes = []any{
	(SubjectKind)(0),   // 0: hub.v1.SubjectKind
	(PayloadType)(0),   // 1: hub.v1.PayloadType
	(*Subject)(nil),    // 2: hub.v1.Subject
	(*PayloadRef)(nil), // 3: hub.v1.PayloadRef
	(*Envelope)(nil),   // 4: hub.v1.Envelope
	nil,                // 5: hub.v1.Envelope.MetaEntry
	(*anypb.Any)(nil),  // 6: google.protobuf.Any
}
var file_hub_v1_envelope_proto_depIdxs = []int32{
	0, // 0: hub.v1.Subject.kind:type_name -> hub.v1.SubjectKind
	2, // 1: hub.v1.Envelope.subject:type_name -> hub.v1.Subject
	1, // 2: hub.v1.Envelope.type:type_name -> hub.v1.PayloadType
	6, // 3: hub.v1.Envelope.payload:type_name -> google.protobuf.Any
	3, // 4: hub.v1.Envelope.payload_ref:type_name -> hub.v1.PayloadRef
	5, // 5: hub.v1.Envelope.meta:type_name -> hub.v1.Envelope.MetaEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hub_v1_envelope_proto_init() }
func file_hub_v1_envelope_proto_init() {
	if File_hub_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_v1_envelope_proto_rawDesc), len(file_hub_v1_envelope_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hub_v1_envelope_proto_goTypes,
		DependencyIndexes: file_hub_v1_envelope_proto_depIdxs,
		EnumInfos:         file_hub_v1_envelope_proto_enumTypes,
		MessageInfos:      file_hub_v1_envelope_proto_msgTypes,
	}.Build()
	File_hub_v1_envelope_proto = out.File
	file_hub_v1_envelope_proto_goTypes = nil
	file_hub_v1_envelope_proto_depIdxs = nil
}
