// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: hub/v1/gateway.proto

package hubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginGateway_ListPlugins_FullMethodName     = "/hub.v1.PluginGateway/ListPlugins"
	PluginGateway_DescribeMessage_FullMethodName = "/hub.v1.PluginGateway/DescribeMessage"
	PluginGateway_GetContract_FullMethodName     = "/hub.v1.PluginGateway/GetContract"
	PluginGateway_Invoke_FullMethodName          = "/hub.v1.PluginGateway/Invoke"
)

// PluginGatewayClient is the client API for PluginGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 插件 → 中台：发现与互调。
//
// 插件之间不直连：直连会绕过中台的治理、审计、熔断与身份体系，与中台定位冲突。
// 同步互调一律经中台代调（A→hub→B），下游复用与 flow 执行同一条
// Invoker / Governor / 审计全链路；发现能力（清单 / 消息端点 / 契约）也只从中台取。
//
// 与 Publish（异步触发 flow，拿不到结果）的分工：需要下游处理结果的同步场景走 Invoke。
//
// **身份与 Publish 同强度**：每个 RPC 都凭 metadata `x-hub-state-token` 反查调用方
// 插件身份，subject 由中台无条件覆盖为调用方——请求信封里自报的 subject 不可信。
//
// **结果语义**：业务层结果（下游拒绝、未授权、超限、成环…）一律走响应字段
// （outcome + reason / issues），只有基础设施故障（未鉴权、下游不可达、内部错误）
// 才返回 gRPC Status——SDK 据此抛类型化异常，调用方不必解析错误字符串。
type PluginGatewayClient interface {
	// 在线插件清单。插件用它找「能调谁」，不必旁路维护硬编码名单
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	// 消息类型 → 生产者 / 消费者。按消息反查上下游，发现可订阅或可调用的数据流
	DescribeMessage(ctx context.Context, in *DescribeMessageRequest, opts ...grpc.CallOption) (*DescribeMessageResponse, error)
	// 插件契约 + 字段级 schema。调别人之前先看它吃什么、吐什么
	GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*GetContractResponse, error)
	// 同步互调 A→hub→B。中台负责鉴权、配额、防环、subject 覆盖与 deadline 夹紧
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
}

type pluginGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginGatewayClient(cc grpc.ClientConnInterface) PluginGatewayClient {
	return &pluginGatewayClient{cc}
}

func (c *pluginGatewayClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, PluginGateway_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginGatewayClient) DescribeMessage(ctx context.Context, in *DescribeMessageRequest, opts ...grpc.CallOption) (*DescribeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeMessageResponse)
	err := c.cc.Invoke(ctx, PluginGateway_DescribeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginGatewayClient) GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*GetContractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContractResponse)
	err := c.cc.Invoke(ctx, PluginGateway_GetContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginGatewayClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, PluginGateway_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginGatewayServer is the server API for PluginGateway service.
// All implementations should embed UnimplementedPluginGatewayServer
// for forward compatibility.
//
// 插件 → 中台：发现与互调。
//
// 插件之间不直连：直连会绕过中台的治理、审计、熔断与身份体系，与中台定位冲突。
// 同步互调一律经中台代调（A→hub→B），下游复用与 flow 执行同一条
// Invoker / Governor / 审计全链路；发现能力（清单 / 消息端点 / 契约）也只从中台取。
//
// 与 Publish（异步触发 flow，拿不到结果）的分工：需要下游处理结果的同步场景走 Invoke。
//
// **身份与 Publish 同强度**：每个 RPC 都凭 metadata `x-hub-state-token` 反查调用方
// 插件身份，subject 由中台无条件覆盖为调用方——请求信封里自报的 subject 不可信。
//
// **结果语义**：业务层结果（下游拒绝、未授权、超限、成环…）一律走响应字段
// （outcome + reason / issues），只有基础设施故障（未鉴权、下游不可达、内部错误）
// 才返回 gRPC Status——SDK 据此抛类型化异常，调用方不必解析错误字符串。
type PluginGatewayServer interface {
	// 在线插件清单。插件用它找「能调谁」，不必旁路维护硬编码名单
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	// 消息类型 → 生产者 / 消费者。按消息反查上下游，发现可订阅或可调用的数据流
	DescribeMessage(context.Context, *DescribeMessageRequest) (*DescribeMessageResponse, error)
	// 插件契约 + 字段级 schema。调别人之前先看它吃什么、吐什么
	GetContract(context.Context, *GetContractRequest) (*GetContractResponse, error)
	// 同步互调 A→hub→B。中台负责鉴权、配额、防环、subject 覆盖与 deadline 夹紧
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
}

// UnimplementedPluginGatewayServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginGatewayServer struct{}

func (UnimplementedPluginGatewayServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedPluginGatewayServer) DescribeMessage(context.Context, *DescribeMessageRequest) (*DescribeMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeMessage not implemented")
}
func (UnimplementedPluginGatewayServer) GetContract(context.Context, *GetContractRequest) (*GetContractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContract not implemented")
}
func (UnimplementedPluginGatewayServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedPluginGatewayServer) testEmbeddedByValue() {}

// UnsafePluginGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginGatewayServer will
// result in compilation errors.
type UnsafePluginGatewayServer interface {
	mustEmbedUnimplementedPluginGatewayServer()
}

func RegisterPluginGatewayServer(s grpc.ServiceRegistrar, srv PluginGatewayServer) {
	// If the following call panics, it indicates UnimplementedPluginGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginGateway_ServiceDesc, srv)
}

func _PluginGateway_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginGatewayServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginGateway_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginGatewayServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginGateway_DescribeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginGatewayServer).DescribeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginGateway_DescribeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginGatewayServer).DescribeMessage(ctx, req.(*DescribeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginGateway_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginGatewayServer).GetContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginGateway_GetContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginGatewayServer).GetContract(ctx, req.(*GetContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginGateway_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginGatewayServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginGateway_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginGatewayServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginGateway_ServiceDesc is the grpc.ServiceDesc for PluginGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.v1.PluginGateway",
	HandlerType: (*PluginGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlugins",
			Handler:    _PluginGateway_ListPlugins_Handler,
		},
		{
			MethodName: "DescribeMessage",
			Handler:    _PluginGateway_DescribeMessage_Handler,
		},
		{
			MethodName: "GetContract",
			Handler:    _PluginGateway_GetContract_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _PluginGateway_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub/v1/gateway.proto",
}
