// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: hub/v1/gateway.proto

package hubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 业务结果分类。基础设施故障不走这里——那会直接返回 gRPC Status。
type InvokeOutcome int32

const (
	InvokeOutcome_INVOKE_OUTCOME_UNSPECIFIED InvokeOutcome = 0
	// 下游 Handle 成功，envelope 即其返回信封
	InvokeOutcome_HANDLED InvokeOutcome = 1
	// 下游 Validate 拒绝，issues 为结构化校验问题
	InvokeOutcome_REJECTED InvokeOutcome = 2
	// 未授权 / 超限 / 成环 / 链深超限 / 下游出错等，reason 说明原因
	InvokeOutcome_ERROR InvokeOutcome = 3
)

// Enum value maps for InvokeOutcome.
var (
	InvokeOutcome_name = map[int32]string{
		0: "INVOKE_OUTCOME_UNSPECIFIED",
		1: "HANDLED",
		2: "REJECTED",
		3: "ERROR",
	}
	InvokeOutcome_value = map[string]int32{
		"INVOKE_OUTCOME_UNSPECIFIED": 0,
		"HANDLED":                    1,
		"REJECTED":                   2,
		"ERROR":                      3,
	}
)

func (x InvokeOutcome) Enum() *InvokeOutcome {
	p := new(InvokeOutcome)
	*p = x
	return p
}

func (x InvokeOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvokeOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (InvokeOutcome) Type() protoreflect.EnumType {
	return &file_hub_v1_gateway_proto_enumTypes[0]
}

func (x InvokeOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvokeOutcome.Descriptor instead.
func (InvokeOutcome) EnumDescriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type ListPluginsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 缺省只列在线（有健康实例）的插件；置 true 时附上离线插件
	IncludeOffline bool `protobuf:"varint,1,opt,name=include_offline,json=includeOffline,proto3" json:"include_offline,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_hub_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ListPluginsRequest) GetIncludeOffline() bool {
	if x != nil {
		return x.IncludeOffline
	}
	return false
}

type PluginSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 已注册的最新版本。多版本共存时在线的不一定是它
	LatestVersion string `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	Online        bool   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	// 当前健康实例数
	InstanceCount uint32 `protobuf:"varint,4,opt,name=instance_count,json=instanceCount,proto3" json:"instance_count,omitempty"`
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginSummary) Reset() {
	*x = PluginSummary{}
	mi := &file_hub_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSummary) ProtoMessage() {}

func (x *PluginSummary) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSummary.ProtoReflect.Descriptor instead.
func (*PluginSummary) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PluginSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginSummary) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *PluginSummary) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PluginSummary) GetInstanceCount() uint32 {
	if x != nil {
		return x.InstanceCount
	}
	return 0
}

func (x *PluginSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginSummary       `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_hub_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginSummary {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type DescribeMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 全限定消息名，与 MessageContract.fq_name 同口径（如 `wms.v1.OrderCreated`）
	FqName        string `protobuf:"bytes,1,opt,name=fq_name,json=fqName,proto3" json:"fq_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeMessageRequest) Reset() {
	*x = DescribeMessageRequest{}
	mi := &file_hub_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeMessageRequest) ProtoMessage() {}

func (x *DescribeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeMessageRequest.ProtoReflect.Descriptor instead.
func (*DescribeMessageRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeMessageRequest) GetFqName() string {
	if x != nil {
		return x.FqName
	}
	return ""
}

type MessageEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 生产 / 消费该消息的插件及其版本
	Plugin        string `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEndpoint) Reset() {
	*x = MessageEndpoint{}
	mi := &file_hub_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEndpoint) ProtoMessage() {}

func (x *MessageEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEndpoint.ProtoReflect.Descriptor instead.
func (*MessageEndpoint) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *MessageEndpoint) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *MessageEndpoint) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DescribeMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 生产者来自 manifest.produces，消费者来自 manifest.consumes
	Producers     []*MessageEndpoint `protobuf:"bytes,1,rep,name=producers,proto3" json:"producers,omitempty"`
	Consumers     []*MessageEndpoint `protobuf:"bytes,2,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeMessageResponse) Reset() {
	*x = DescribeMessageResponse{}
	mi := &file_hub_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeMessageResponse) ProtoMessage() {}

func (x *DescribeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeMessageResponse.ProtoReflect.Descriptor instead.
func (*DescribeMessageResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeMessageResponse) GetProducers() []*MessageEndpoint {
	if x != nil {
		return x.Producers
	}
	return nil
}

func (x *DescribeMessageResponse) GetConsumers() []*MessageEndpoint {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type GetContractRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Plugin string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	// 可空：空 = 取最新已注册版本
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// 可空：空 = 不展开单个消息的字段级 schema（只要整份契约）
	FqName        string `protobuf:"bytes,3,opt,name=fq_name,json=fqName,proto3" json:"fq_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	mi := &file_hub_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetContractRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *GetContractRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetContractRequest) GetFqName() string {
	if x != nil {
		return x.FqName
	}
	return ""
}

type GetContractResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// 复用 plugin.proto 的消息契约
	Produces []*MessageContract `protobuf:"bytes,3,rep,name=produces,proto3" json:"produces,omitempty"`
	Consumes []*MessageContract `protobuf:"bytes,4,rep,name=consumes,proto3" json:"consumes,omitempty"`
	// 本插件声明可调用的目标插件名（语义同 PluginManifest.invokes）
	Invokes []string `protobuf:"bytes,5,rep,name=invokes,proto3" json:"invokes,omitempty"`
	// 复用 plugin.proto 的工具声明
	Tools []*ToolDecl `protobuf:"bytes,6,rep,name=tools,proto3" json:"tools,omitempty"`
	// fq_name 非空时：该消息的字段级 schema（JSON，由注册的 descriptor 摊平）；否则为空
	SchemaJson    string `protobuf:"bytes,7,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractResponse) Reset() {
	*x = GetContractResponse{}
	mi := &file_hub_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractResponse) ProtoMessage() {}

func (x *GetContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractResponse.ProtoReflect.Descriptor instead.
func (*GetContractResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *GetContractResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetContractResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetContractResponse) GetProduces() []*MessageContract {
	if x != nil {
		return x.Produces
	}
	return nil
}

func (x *GetContractResponse) GetConsumes() []*MessageContract {
	if x != nil {
		return x.Consumes
	}
	return nil
}

func (x *GetContractResponse) GetInvokes() []string {
	if x != nil {
		return x.Invokes
	}
	return nil
}

func (x *GetContractResponse) GetTools() []*ToolDecl {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GetContractResponse) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标插件名
	Plugin string `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	// 可空 = 目标最新版本
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// 调用方构造的信封：message_id / type / payload / deadline_ms 必填。
	// subject 会被中台无条件覆盖为调用方，填了也没用。
	// Envelope.meta 是唯一自由携带通道：`hub.call_chain`（复制自调用方收到的信封）
	// 等经它传递，中台据此防互调成环。
	Envelope *Envelope `protobuf:"bytes,3,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// 本次调用的超时预算。实际 deadline = min(传入 deadline_ms, now + timeout_ms)：
	// 既不允许顶掉更早的整体 deadline，也不会比它更晚
	TimeoutMs     uint32 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_hub_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *InvokeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InvokeRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *InvokeRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type InvokeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Outcome InvokeOutcome          `protobuf:"varint,1,opt,name=outcome,proto3,enum=hub.v1.InvokeOutcome" json:"outcome,omitempty"`
	// 仅 HANDLED 时有值：下游 Handle 返回的信封
	Envelope *Envelope `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// 仅 REJECTED 时有值：目标插件 Validate 的 issues（复用 plugin.proto）
	Issues []*ValidationIssue `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	// ERROR / REJECTED 的人类可读原因
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// 中台侧整备 + 下游处理的总耗时
	ElapsedMs     uint64 `protobuf:"varint,5,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_hub_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeResponse) GetOutcome() InvokeOutcome {
	if x != nil {
		return x.Outcome
	}
	return InvokeOutcome_INVOKE_OUTCOME_UNSPECIFIED
}

func (x *InvokeResponse) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *InvokeResponse) GetIssues() []*ValidationIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *InvokeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InvokeResponse) GetElapsedMs() uint64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

var File_hub_v1_gateway_proto protoreflect.FileDescriptor

const file_hub_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x14hub/v1/gateway.proto\x12\x06hub.v1\x1a\x15hub/v1/envelope.proto\x1a\x13hub/v1/plugin.proto\"=\n" +
	"\x12ListPluginsRequest\x12'\n" +
	"\x0finclude_offline\x18\x01 \x01(\bR\x0eincludeOffline\"\xab\x01\n" +
	"\rPluginSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\tR\rlatestVersion\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12%\n" +
	"\x0einstance_count\x18\x04 \x01(\rR\rinstanceCount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"F\n" +
	"\x13ListPluginsResponse\x12/\n" +
	"\aplugins\x18\x01 \x03(\v2\x15.hub.v1.PluginSummaryR\aplugins\"1\n" +
	"\x16DescribeMessageRequest\x12\x17\n" +
	"\afq_name\x18\x01 \x01(\tR\x06fqName\"C\n" +
	"\x0fMessageEndpoint\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x87\x01\n" +
	"\x17DescribeMessageResponse\x125\n" +
	"\tproducers\x18\x01 \x03(\v2\x17.hub.v1.MessageEndpointR\tproducers\x125\n" +
	"\tconsumers\x18\x02 \x03(\v2\x17.hub.v1.MessageEndpointR\tconsumers\"_\n" +
	"\x12GetContractRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x17\n" +
	"\afq_name\x18\x03 \x01(\tR\x06fqName\"\x90\x02\n" +
	"\x13GetContractResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x123\n" +
	"\bproduces\x18\x03 \x03(\v2\x17.hub.v1.MessageContractR\bproduces\x123\n" +
	"\bconsumes\x18\x04 \x03(\v2\x17.hub.v1.MessageContractR\bconsumes\x12\x18\n" +
	"\ainvokes\x18\x05 \x03(\tR\ainvokes\x12&\n" +
	"\x05tools\x18\x06 \x03(\v2\x10.hub.v1.ToolDeclR\x05tools\x12\x1f\n" +
	"\vschema_json\x18\a \x01(\tR\n" +
	"schemaJson\"\x8e\x01\n" +
	"\rInvokeRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12,\n" +
	"\benvelope\x18\x03 \x01(\v2\x10.hub.v1.EnvelopeR\benvelope\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\"\xd7\x01\n" +
	"\x0eInvokeResponse\x12/\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x15.hub.v1.InvokeOutcomeR\aoutcome\x12,\n" +
	"\benvelope\x18\x02 \x01(\v2\x10.hub.v1.EnvelopeR\benvelope\x12/\n" +
	"\x06issues\x18\x03 \x03(\v2\x17.hub.v1.ValidationIssueR\x06issues\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x05 \x01(\x04R\telapsedMs*U\n" +
	"\rInvokeOutcome\x12\x1e\n" +
	"\x1aINVOKE_OUTCOME_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aHANDLED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\xac\x02\n" +
	"\rPluginGateway\x12F\n" +
	"\vListPlugins\x12\x1a.hub.v1.ListPluginsRequest\x1a\x1b.hub.v1.ListPluginsResponse\x12R\n" +
	"\x0fDescribeMessage\x12\x1e.hub.v1.DescribeMessageRequest\x1a\x1f.hub.v1.DescribeMessageResponse\x12F\n" +
	"\vGetContract\x12\x1a.hub.v1.GetContractRequest\x1a\x1b.hub.v1.GetContractResponse\x127\n" +
	"\x06Invoke\x12\x15.hub.v1.InvokeRequest\x1a\x16.hub.v1.InvokeResponseBIZGgithub.com/mahingbun-dev/anc-hub/sdk/go/proto/hubv1;hubv1b\x06proto3"

var (
	file_hub_v1_gateway_proto_rawDescOnce sync.Once
	file_hub_v1_gateway_proto_rawDescData []byte
)

func file_hub_v1_gateway_proto_rawDescGZIP() []byte {
	file_hub_v1_gateway_proto_rawDescOnce.Do(func() {
		file_hub_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_v1_gateway_proto_rawDesc), len(file_hub_v1_gateway_proto_rawDesc)))
	})
	return file_hub_v1_gateway_proto_rawDescData
}

var file_hub_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hub_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hub_v1_gateway_proto_goTypes = []any{
	(InvokeOutcome)(0),              // 0: hub.v1.InvokeOutcome
	(*ListPluginsRequest)(nil),      // 1: hub.v1.ListPluginsRequest
	(*PluginSummary)(nil),           // 2: hub.v1.PluginSummary
	(*ListPluginsResponse)(nil),     // 3: hub.v1.ListPluginsResponse
	(*DescribeMessageRequest)(nil),  // 4: hub.v1.DescribeMessageRequest
	(*MessageEndpoint)(nil),         // 5: hub.v1.MessageEndpoint
	(*DescribeMessageResponse)(nil), // 6: hub.v1.DescribeMessageResponse
	(*GetContractRequest)(nil),      // 7: hub.v1.GetContractRequest
	(*GetContractResponse)(nil),     // 8: hub.v1.GetContractResponse
	(*InvokeRequest)(nil),           // 9: hub.v1.InvokeRequest
	(*InvokeResponse)(nil),          // 10: hub.v1.InvokeResponse
	(*MessageContract)(nil),         // 11: hub.v1.MessageContract
	(*ToolDecl)(nil),                // 12: hub.v1.ToolDecl
	(*Envelope)(nil),                // 13: hub.v1.Envelope
	(*ValidationIssue)(nil),         // 14: hub.v1.ValidationIssue
}
var file_hub_v1_gateway_proto_depIdxs = []int32{
	2,  // 0: hub.v1.ListPluginsResponse.plugins:type_name -> hub.v1.PluginSummary
	5,  // 1: hub.v1.DescribeMessageResponse.producers:type_name -> hub.v1.MessageEndpoint
	5,  // 2: hub.v1.DescribeMessageResponse.consumers:type_name -> hub.v1.MessageEndpoint
	11, // 3: hub.v1.GetContractResponse.produces:type_name -> hub.v1.MessageContract
	11, // 4: hub.v1.GetContractResponse.consumes:type_name -> hub.v1.MessageContract
	12, // 5: hub.v1.GetContractResponse.tools:type_name -> hub.v1.ToolDecl
	13, // 6: hub.v1.InvokeRequest.envelope:type_name -> hub.v1.Envelope
	0,  // 7: hub.v1.InvokeResponse.outcome:type_name -> hub.v1.InvokeOutcome
	13, // 8: hub.v1.InvokeResponse.envelope:type_name -> hub.v1.Envelope
	14, // 9: hub.v1.InvokeResponse.issues:type_name -> hub.v1.ValidationIssue
	1,  // 10: hub.v1.PluginGateway.ListPlugins:input_type -> hub.v1.ListPluginsRequest
	4,  // 11: hub.v1.PluginGateway.DescribeMessage:input_type -> hub.v1.DescribeMessageRequest
	7,  // 12: hub.v1.PluginGateway.GetContract:input_type -> hub.v1.GetContractRequest
	9,  // 13: hub.v1.PluginGateway.Invoke:input_type -> hub.v1.InvokeRequest
	3,  // 14: hub.v1.PluginGateway.ListPlugins:output_type -> hub.v1.ListPluginsResponse
	6,  // 15: hub.v1.PluginGateway.DescribeMessage:output_type -> hub.v1.DescribeMessageResponse
	8,  // 16: hub.v1.PluginGateway.GetContract:output_type -> hub.v1.GetContractResponse
	10, // 17: hub.v1.PluginGateway.Invoke:output_type -> hub.v1.InvokeResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_hub_v1_gateway_proto_init() }
func file_hub_v1_gateway_proto_init() {
	if File_hub_v1_gateway_proto != nil {
		return
	}
	file_hub_v1_envelope_proto_init()
	file_hub_v1_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_v1_gateway_proto_rawDesc), len(file_hub_v1_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_v1_gateway_proto_goTypes,
		DependencyIndexes: file_hub_v1_gateway_proto_depIdxs,
		EnumInfos:         file_hub_v1_gateway_proto_enumTypes,
		MessageInfos:      file_hub_v1_gateway_proto_msgTypes,
	}.Build()
	File_hub_v1_gateway_proto = out.File
	file_hub_v1_gateway_proto_goTypes = nil
	file_hub_v1_gateway_proto_depIdxs = nil
}
