// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: hub/v1/plugin.proto

package hubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginRuntime_Describe_FullMethodName     = "/hub.v1.PluginRuntime/Describe"
	PluginRuntime_Validate_FullMethodName     = "/hub.v1.PluginRuntime/Validate"
	PluginRuntime_Handle_FullMethodName       = "/hub.v1.PluginRuntime/Handle"
	PluginRuntime_HandleStream_FullMethodName = "/hub.v1.PluginRuntime/HandleStream"
	PluginRuntime_Health_FullMethodName       = "/hub.v1.PluginRuntime/Health"
)

// PluginRuntimeClient is the client API for PluginRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 中台 → 插件。
//
// 每个插件必须实现全部方法，缺一不可：
//   - Validate 是「数据校验规则」，数据进来先过它，通过后才进 Handle
//   - Handle 是「插件体」，自主实现的数据输入输出
//
// 二者同版本发布，规则与实现不可能漂移。
//
// 中台按插件自注册时上报的 advertise 地址直连，不要求与中台同机。
type PluginRuntimeClient interface {
	// 拉取 manifest。中台用它核对插件自述与注册时提交的内容是否一致。
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*PluginManifest, error)
	// 校验器。校验失败按 manifest 的 validation 策略处理（默认拒绝）。
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	// 插件体。
	Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error)
	// 逐条结果的流式版本（大报文 / 多条输出）。中台侧走 server-streaming 转发。
	HandleStream(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HandleResponse], error)
	// 健康探测。中台在注册时与心跳周期内调用。
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type pluginRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginRuntimeClient(cc grpc.ClientConnInterface) PluginRuntimeClient {
	return &pluginRuntimeClient{cc}
}

func (c *pluginRuntimeClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*PluginManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginManifest)
	err := c.cc.Invoke(ctx, PluginRuntime_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, PluginRuntime_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleResponse)
	err := c.cc.Invoke(ctx, PluginRuntime_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) HandleStream(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HandleResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginRuntime_ServiceDesc.Streams[0], PluginRuntime_HandleStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HandleRequest, HandleResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginRuntime_HandleStreamClient = grpc.ServerStreamingClient[HandleResponse]

func (c *pluginRuntimeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginRuntime_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginRuntimeServer is the server API for PluginRuntime service.
// All implementations should embed UnimplementedPluginRuntimeServer
// for forward compatibility.
//
// 中台 → 插件。
//
// 每个插件必须实现全部方法，缺一不可：
//   - Validate 是「数据校验规则」，数据进来先过它，通过后才进 Handle
//   - Handle 是「插件体」，自主实现的数据输入输出
//
// 二者同版本发布，规则与实现不可能漂移。
//
// 中台按插件自注册时上报的 advertise 地址直连，不要求与中台同机。
type PluginRuntimeServer interface {
	// 拉取 manifest。中台用它核对插件自述与注册时提交的内容是否一致。
	Describe(context.Context, *DescribeRequest) (*PluginManifest, error)
	// 校验器。校验失败按 manifest 的 validation 策略处理（默认拒绝）。
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	// 插件体。
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
	// 逐条结果的流式版本（大报文 / 多条输出）。中台侧走 server-streaming 转发。
	HandleStream(*HandleRequest, grpc.ServerStreamingServer[HandleResponse]) error
	// 健康探测。中台在注册时与心跳周期内调用。
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

// UnimplementedPluginRuntimeServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginRuntimeServer struct{}

func (UnimplementedPluginRuntimeServer) Describe(context.Context, *DescribeRequest) (*PluginManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginRuntimeServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedPluginRuntimeServer) Handle(context.Context, *HandleRequest) (*HandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedPluginRuntimeServer) HandleStream(*HandleRequest, grpc.ServerStreamingServer[HandleResponse]) error {
	return status.Error(codes.Unimplemented, "method HandleStream not implemented")
}
func (UnimplementedPluginRuntimeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginRuntimeServer) testEmbeddedByValue() {}

// UnsafePluginRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginRuntimeServer will
// result in compilation errors.
type UnsafePluginRuntimeServer interface {
	mustEmbedUnimplementedPluginRuntimeServer()
}

func RegisterPluginRuntimeServer(s grpc.ServiceRegistrar, srv PluginRuntimeServer) {
	// If the following call panics, it indicates UnimplementedPluginRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginRuntime_ServiceDesc, srv)
}

func _PluginRuntime_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Handle(ctx, req.(*HandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_HandleStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HandleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginRuntimeServer).HandleStream(m, &grpc.GenericServerStream[HandleRequest, HandleResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginRuntime_HandleStreamServer = grpc.ServerStreamingServer[HandleResponse]

func _PluginRuntime_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginRuntime_ServiceDesc is the grpc.ServiceDesc for PluginRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.v1.PluginRuntime",
	HandlerType: (*PluginRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PluginRuntime_Describe_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _PluginRuntime_Validate_Handler,
		},
		{
			MethodName: "Handle",
			Handler:    _PluginRuntime_Handle_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PluginRuntime_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleStream",
			Handler:       _PluginRuntime_HandleStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hub/v1/plugin.proto",
}
