// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: hub/v1/plugin.proto

package hubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailureAction int32

const (
	FailureAction_FAILURE_ACTION_UNSPECIFIED FailureAction = 0
	// 拒绝：短路当前链路并返回结构化错误（默认）
	FailureAction_FAILURE_ACTION_REJECT FailureAction = 1
	// 影子模式：放行但记录告警。用于新规则上线前的观察期。
	FailureAction_FAILURE_ACTION_SHADOW FailureAction = 2
)

// Enum value maps for FailureAction.
var (
	FailureAction_name = map[int32]string{
		0: "FAILURE_ACTION_UNSPECIFIED",
		1: "FAILURE_ACTION_REJECT",
		2: "FAILURE_ACTION_SHADOW",
	}
	FailureAction_value = map[string]int32{
		"FAILURE_ACTION_UNSPECIFIED": 0,
		"FAILURE_ACTION_REJECT":      1,
		"FAILURE_ACTION_SHADOW":      2,
	}
)

func (x FailureAction) Enum() *FailureAction {
	p := new(FailureAction)
	*p = x
	return p
}

func (x FailureAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureAction) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (FailureAction) Type() protoreflect.EnumType {
	return &file_hub_v1_plugin_proto_enumTypes[0]
}

func (x FailureAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureAction.Descriptor instead.
func (FailureAction) EnumDescriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_ERROR       Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_ERROR",
		2: "SEVERITY_WARNING",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_ERROR":       1,
		"SEVERITY_WARNING":     2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_hub_v1_plugin_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{1}
}

// 插件自述清单。中台据此做契约校验、编排校验与 MCP 工具聚合。
type PluginManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 插件名（逻辑插件），多版本共存时同名不同 version
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 语义化版本。flow 通过版本约束（如 ^2.1）锁定实例。
	Version     string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// 负责团队，用于治理与告警归口
	Owner string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	// 消费的消息类型：上游 produces 必须与这里的 fq_name 完全一致才能连成一条 flow
	Consumes []*MessageContract `protobuf:"bytes,5,rep,name=consumes,proto3" json:"consumes,omitempty"`
	// 生产的消息类型
	Produces []*MessageContract `protobuf:"bytes,6,rep,name=produces,proto3" json:"produces,omitempty"`
	// 暴露给 agent 的能力。中台自动聚合为统一 MCP 工具面，名称加 `插件名__` 前缀。
	Tools      []*ToolDecl       `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	Validation *ValidationPolicy `protobuf:"bytes,8,opt,name=validation,proto3" json:"validation,omitempty"`
	// 声明可调用的目标插件名（插件互调的权限名单）。
	//
	// 注册时**可选**：不带此字段的老插件 / 无互调需求的插件无需改动，是否放行其互调
	// 由中台 `HUB_PLUGIN_CALL_POLICY`（allow|declared，默认 allow）决定；一旦声明，
	// 中台在调用期强制校验目标插件是否在名单内，不在一律拒绝。
	// manifest 以字节存库，追加字段对旧 hub / 旧插件双向兼容，无迁移。
	Invokes       []string `protobuf:"bytes,9,rep,name=invokes,proto3" json:"invokes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_hub_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginManifest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PluginManifest) GetConsumes() []*MessageContract {
	if x != nil {
		return x.Consumes
	}
	return nil
}

func (x *PluginManifest) GetProduces() []*MessageContract {
	if x != nil {
		return x.Produces
	}
	return nil
}

func (x *PluginManifest) GetTools() []*ToolDecl {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *PluginManifest) GetValidation() *ValidationPolicy {
	if x != nil {
		return x.Validation
	}
	return nil
}

func (x *PluginManifest) GetInvokes() []string {
	if x != nil {
		return x.Invokes
	}
	return nil
}

type MessageContract struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 全限定消息名，例如 `wms.v1.OrderCreated` —— 契约的唯一标识。
	// 改名或改包名视为破坏性变更，注册会被拒绝。
	FqName        string `protobuf:"bytes,1,opt,name=fq_name,json=fqName,proto3" json:"fq_name,omitempty"`
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContract) Reset() {
	*x = MessageContract{}
	mi := &file_hub_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContract) ProtoMessage() {}

func (x *MessageContract) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContract.ProtoReflect.Descriptor instead.
func (*MessageContract) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *MessageContract) GetFqName() string {
	if x != nil {
		return x.FqName
	}
	return ""
}

func (x *MessageContract) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ToolDecl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 短名。中台聚合时加前缀，插件间重名不会冲突。
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// MCP 工具的入参 JSON Schema（字符串形式）
	InputSchemaJson string `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	// 是否属于「改变生产走向」的操作。为 true 时 agent 只能提交草稿，需人工审批后生效。
	RequiresApproval bool `protobuf:"varint,4,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolDecl) Reset() {
	*x = ToolDecl{}
	mi := &file_hub_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDecl) ProtoMessage() {}

func (x *ToolDecl) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDecl.ProtoReflect.Descriptor instead.
func (*ToolDecl) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDecl) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDecl) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDecl) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

func (x *ToolDecl) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

type ValidationPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnFailure     FailureAction          `protobuf:"varint,1,opt,name=on_failure,json=onFailure,proto3,enum=hub.v1.FailureAction" json:"on_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationPolicy) Reset() {
	*x = ValidationPolicy{}
	mi := &file_hub_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationPolicy) ProtoMessage() {}

func (x *ValidationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationPolicy.ProtoReflect.Descriptor instead.
func (*ValidationPolicy) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ValidationPolicy) GetOnFailure() FailureAction {
	if x != nil {
		return x.OnFailure
	}
	return FailureAction_FAILURE_ACTION_UNSPECIFIED
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_hub_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{4}
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_hub_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Issues        []*ValidationIssue     `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_hub_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetIssues() []*ValidationIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type ValidationIssue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 字段路径，例如 `payload.items[2].sku`
	Path          string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Message       string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Severity      Severity `protobuf:"varint,3,opt,name=severity,proto3,enum=hub.v1.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationIssue) Reset() {
	*x = ValidationIssue{}
	mi := &file_hub_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationIssue) ProtoMessage() {}

func (x *ValidationIssue) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationIssue.ProtoReflect.Descriptor instead.
func (*ValidationIssue) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ValidationIssue) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValidationIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationIssue) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

type HandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequest) Reset() {
	*x = HandleRequest{}
	mi := &file_hub_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequest) ProtoMessage() {}

func (x *HandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequest.ProtoReflect.Descriptor instead.
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *HandleRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type HandleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 输出信封。中台会校验其 payload 的全限定名是否落在 manifest.produces 内。
	Envelope      *Envelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleResponse) Reset() {
	*x = HandleResponse{}
	mi := &file_hub_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResponse) ProtoMessage() {}

func (x *HandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResponse.ProtoReflect.Descriptor instead.
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *HandleResponse) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_hub_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_hub_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hub_v1_plugin_proto protoreflect.FileDescriptor

const file_hub_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x13hub/v1/plugin.proto\x12\x06hub.v1\x1a\x15hub/v1/envelope.proto\"\xdc\x02\n" +
	"\x0ePluginManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x123\n" +
	"\bconsumes\x18\x05 \x03(\v2\x17.hub.v1.MessageContractR\bconsumes\x123\n" +
	"\bproduces\x18\x06 \x03(\v2\x17.hub.v1.MessageContractR\bproduces\x12&\n" +
	"\x05tools\x18\a \x03(\v2\x10.hub.v1.ToolDeclR\x05tools\x128\n" +
	"\n" +
	"validation\x18\b \x01(\v2\x18.hub.v1.ValidationPolicyR\n" +
	"validation\x12\x18\n" +
	"\ainvokes\x18\t \x03(\tR\ainvokes\"L\n" +
	"\x0fMessageContract\x12\x17\n" +
	"\afq_name\x18\x01 \x01(\tR\x06fqName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x99\x01\n" +
	"\bToolDecl\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\tR\x0finputSchemaJson\x12+\n" +
	"\x11requires_approval\x18\x04 \x01(\bR\x10requiresApproval\"H\n" +
	"\x10ValidationPolicy\x124\n" +
	"\n" +
	"on_failure\x18\x01 \x01(\x0e2\x15.hub.v1.FailureActionR\tonFailure\"\x11\n" +
	"\x0fDescribeRequest\"?\n" +
	"\x0fValidateRequest\x12,\n" +
	"\benvelope\x18\x01 \x01(\v2\x10.hub.v1.EnvelopeR\benvelope\"Y\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12/\n" +
	"\x06issues\x18\x02 \x03(\v2\x17.hub.v1.ValidationIssueR\x06issues\"m\n" +
	"\x0fValidationIssue\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x10.hub.v1.SeverityR\bseverity\"=\n" +
	"\rHandleRequest\x12,\n" +
	"\benvelope\x18\x01 \x01(\v2\x10.hub.v1.EnvelopeR\benvelope\">\n" +
	"\x0eHandleResponse\x12,\n" +
	"\benvelope\x18\x01 \x01(\v2\x10.hub.v1.EnvelopeR\benvelope\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*e\n" +
	"\rFailureAction\x12\x1e\n" +
	"\x1aFAILURE_ACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FAILURE_ACTION_REJECT\x10\x01\x12\x19\n" +
	"\x15FAILURE_ACTION_SHADOW\x10\x02*N\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x022\xbe\x02\n" +
	"\rPluginRuntime\x12;\n" +
	"\bDescribe\x12\x17.hub.v1.DescribeRequest\x1a\x16.hub.v1.PluginManifest\x12=\n" +
	"\bValidate\x12\x17.hub.v1.ValidateRequest\x1a\x18.hub.v1.ValidateResponse\x127\n" +
	"\x06Handle\x12\x15.hub.v1.HandleRequest\x1a\x16.hub.v1.HandleResponse\x12?\n" +
	"\fHandleStream\x12\x15.hub.v1.HandleRequest\x1a\x16.hub.v1.HandleResponse0\x01\x127\n" +
	"\x06Health\x12\x15.hub.v1.HealthRequest\x1a\x16.hub.v1.HealthResponseB>Z<github.com/mahingbun-dev/plugin-hub/sdk/go/proto/hubv1;hubv1b\x06proto3"

var (
	file_hub_v1_plugin_proto_rawDescOnce sync.Once
	file_hub_v1_plugin_proto_rawDescData []byte
)

func file_hub_v1_plugin_proto_rawDescGZIP() []byte {
	file_hub_v1_plugin_proto_rawDescOnce.Do(func() {
		file_hub_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_v1_plugin_proto_rawDesc), len(file_hub_v1_plugin_proto_rawDesc)))
	})
	return file_hub_v1_plugin_proto_rawDescData
}

var file_hub_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hub_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_hub_v1_plugin_proto_goTypes = []any{
	(FailureAction)(0),       // 0: hub.v1.FailureAction
	(Severity)(0),            // 1: hub.v1.Severity
	(*PluginManifest)(nil),   // 2: hub.v1.PluginManifest
	(*MessageContract)(nil),  // 3: hub.v1.MessageContract
	(*ToolDecl)(nil),         // 4: hub.v1.ToolDecl
	(*ValidationPolicy)(nil), // 5: hub.v1.ValidationPolicy
	(*DescribeRequest)(nil),  // 6: hub.v1.DescribeRequest
	(*ValidateRequest)(nil),  // 7: hub.v1.ValidateRequest
	(*ValidateResponse)(nil), // 8: hub.v1.ValidateResponse
	(*ValidationIssue)(nil),  // 9: hub.v1.ValidationIssue
	(*HandleRequest)(nil),    // 10: hub.v1.HandleRequest
	(*HandleResponse)(nil),   // 11: hub.v1.HandleResponse
	(*HealthRequest)(nil),    // 12: hub.v1.HealthRequest
	(*HealthResponse)(nil),   // 13: hub.v1.HealthResponse
	(*Envelope)(nil),         // 14: hub.v1.Envelope
}
var file_hub_v1_plugin_proto_depIdxs = []int32{
	3,  // 0: hub.v1.PluginManifest.consumes:type_name -> hub.v1.MessageContract
	3,  // 1: hub.v1.PluginManifest.produces:type_name -> hub.v1.MessageContract
	4,  // 2: hub.v1.PluginManifest.tools:type_name -> hub.v1.ToolDecl
	5,  // 3: hub.v1.PluginManifest.validation:type_name -> hub.v1.ValidationPolicy
	0,  // 4: hub.v1.ValidationPolicy.on_failure:type_name -> hub.v1.FailureAction
	14, // 5: hub.v1.ValidateRequest.envelope:type_name -> hub.v1.Envelope
	9,  // 6: hub.v1.ValidateResponse.issues:type_name -> hub.v1.ValidationIssue
	1,  // 7: hub.v1.ValidationIssue.severity:type_name -> hub.v1.Severity
	14, // 8: hub.v1.HandleRequest.envelope:type_name -> hub.v1.Envelope
	14, // 9: hub.v1.HandleResponse.envelope:type_name -> hub.v1.Envelope
	6,  // 10: hub.v1.PluginRuntime.Describe:input_type -> hub.v1.DescribeRequest
	7,  // 11: hub.v1.PluginRuntime.Validate:input_type -> hub.v1.ValidateRequest
	10, // 12: hub.v1.PluginRuntime.Handle:input_type -> hub.v1.HandleRequest
	10, // 13: hub.v1.PluginRuntime.HandleStream:input_type -> hub.v1.HandleRequest
	12, // 14: hub.v1.PluginRuntime.Health:input_type -> hub.v1.HealthRequest
	2,  // 15: hub.v1.PluginRuntime.Describe:output_type -> hub.v1.PluginManifest
	8,  // 16: hub.v1.PluginRuntime.Validate:output_type -> hub.v1.ValidateResponse
	11, // 17: hub.v1.PluginRuntime.Handle:output_type -> hub.v1.HandleResponse
	11, // 18: hub.v1.PluginRuntime.HandleStream:output_type -> hub.v1.HandleResponse
	13, // 19: hub.v1.PluginRuntime.Health:output_type -> hub.v1.HealthResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_hub_v1_plugin_proto_init() }
func file_hub_v1_plugin_proto_init() {
	if File_hub_v1_plugin_proto != nil {
		return
	}
	file_hub_v1_envelope_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_v1_plugin_proto_rawDesc), len(file_hub_v1_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_v1_plugin_proto_goTypes,
		DependencyIndexes: file_hub_v1_plugin_proto_depIdxs,
		EnumInfos:         file_hub_v1_plugin_proto_enumTypes,
		MessageInfos:      file_hub_v1_plugin_proto_msgTypes,
	}.Build()
	File_hub_v1_plugin_proto = out.File
	file_hub_v1_plugin_proto_goTypes = nil
	file_hub_v1_plugin_proto_depIdxs = nil
}
