// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: hub/v1/registry.proto

package hubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RejectCode int32

const (
	RejectCode_REJECT_CODE_UNSPECIFIED RejectCode = 0
	// 可达性探测失败：地址不通或 Health 返回不健康
	RejectCode_REJECT_CODE_UNREACHABLE RejectCode = 1
	// descriptor 无法解析
	RejectCode_REJECT_CODE_DESCRIPTOR_INVALID RejectCode = 2
	// 字段级不兼容：删字段、改类型、改编号、改包名或消息名
	RejectCode_REJECT_CODE_BREAKING_CHANGE RejectCode = 3
	// MCP 工具名与既有插件冲突
	RejectCode_REJECT_CODE_TOOL_CONFLICT RejectCode = 4
	// 同一 (插件名, 版本) 下已有实例，但 manifest 不一致
	RejectCode_REJECT_CODE_VERSION_CONFLICT RejectCode = 5
	// manifest 本身非法（缺 name/version、produces 不在 descriptor 中定义等）
	RejectCode_REJECT_CODE_MANIFEST_INVALID RejectCode = 6
	RejectCode_REJECT_CODE_INTERNAL         RejectCode = 7
	// instance_id 不可用：为空、超长，或已被**其它插件**占用。
	//
	// 实例行同时是 HubState 状态凭证的载体，而 instance_id 由插件自己生成。顶掉别的
	// 插件的行会让原插件从自己的实例列表里消失（选中它时 NoHealthyInstance），而它的
	// 心跳仍按 instance_id 命中、察觉不到丢了注册——两边于是每次重注册都互相顶掉。
	// 所以属主不是本插件就拒绝；同一插件换版本/重启则放行（实例行随之迁移）。
	RejectCode_REJECT_CODE_INSTANCE_CONFLICT RejectCode = 8
)

// Enum value maps for RejectCode.
var (
	RejectCode_name = map[int32]string{
		0: "REJECT_CODE_UNSPECIFIED",
		1: "REJECT_CODE_UNREACHABLE",
		2: "REJECT_CODE_DESCRIPTOR_INVALID",
		3: "REJECT_CODE_BREAKING_CHANGE",
		4: "REJECT_CODE_TOOL_CONFLICT",
		5: "REJECT_CODE_VERSION_CONFLICT",
		6: "REJECT_CODE_MANIFEST_INVALID",
		7: "REJECT_CODE_INTERNAL",
		8: "REJECT_CODE_INSTANCE_CONFLICT",
	}
	RejectCode_value = map[string]int32{
		"REJECT_CODE_UNSPECIFIED":        0,
		"REJECT_CODE_UNREACHABLE":        1,
		"REJECT_CODE_DESCRIPTOR_INVALID": 2,
		"REJECT_CODE_BREAKING_CHANGE":    3,
		"REJECT_CODE_TOOL_CONFLICT":      4,
		"REJECT_CODE_VERSION_CONFLICT":   5,
		"REJECT_CODE_MANIFEST_INVALID":   6,
		"REJECT_CODE_INTERNAL":           7,
		"REJECT_CODE_INSTANCE_CONFLICT":  8,
	}
)

func (x RejectCode) Enum() *RejectCode {
	p := new(RejectCode)
	*p = x
	return p
}

func (x RejectCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RejectCode) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_v1_registry_proto_enumTypes[0].Descriptor()
}

func (RejectCode) Type() protoreflect.EnumType {
	return &file_hub_v1_registry_proto_enumTypes[0]
}

func (x RejectCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RejectCode.Descriptor instead.
func (RejectCode) EnumDescriptor() ([]byte, []int) {
	return file_hub_v1_registry_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PluginName string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Version    string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// 实例唯一标识（容器启动时生成）。同一插件的多副本共用一个插件定义，
	// 实例各自独立，按 (插件名, 版本) 归组。
	InstanceId string `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// 中台可达的 gRPC 地址。中台按此地址回调插件，注册时会先探测连通性，
	// 避免出现「注册成功但永远调不通」这种最难排查的状态。
	AdvertiseAddr string          `protobuf:"bytes,4,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	Manifest      *PluginManifest `protobuf:"bytes,5,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// `google.protobuf.FileDescriptorSet` 的序列化字节。
	// 中台据此建立契约基线，做字段级兼容检查。只发本插件自己的 proto，不含依赖。
	DescriptorSet []byte `protobuf:"bytes,6,opt,name=descriptor_set,json=descriptorSet,proto3" json:"descriptor_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_hub_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterRequest) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *RegisterRequest) GetManifest() *PluginManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *RegisterRequest) GetDescriptorSet() []byte {
	if x != nil {
		return x.DescriptorSet
	}
	return nil
}

type RegisterResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Accepted   bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	InstanceId string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// 中台指定的心跳周期，插件应遵守
	HeartbeatIntervalSeconds int32        `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	Rejections               []*Rejection `protobuf:"bytes,4,rep,name=rejections,proto3" json:"rejections,omitempty"`
	Warnings                 []string     `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// 外置状态（HubState）凭证。插件调用 HubState 时经 gRPC metadata
	// `x-hub-state-token` 携带，中台据此确定插件身份并强制加命名空间前缀。
	//
	// 每次注册轮换：重复注册视为进程重启，旧凭证立即失效。
	// 空值表示该实例不可使用 HubState（迁移前登记的旧行）。
	StateToken    string `protobuf:"bytes,6,opt,name=state_token,json=stateToken,proto3" json:"state_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_hub_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetRejections() []*Rejection {
	if x != nil {
		return x.Rejections
	}
	return nil
}

func (x *RegisterResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *RegisterResponse) GetStateToken() string {
	if x != nil {
		return x.StateToken
	}
	return ""
}

type Rejection struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    RejectCode             `protobuf:"varint,1,opt,name=code,proto3,enum=hub.v1.RejectCode" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 具体细节，例如「字段 wms.v1.Order.sku 由 string 改为 int64」
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rejection) Reset() {
	*x = Rejection{}
	mi := &file_hub_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejection) ProtoMessage() {}

func (x *Rejection) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejection.ProtoReflect.Descriptor instead.
func (*Rejection) Descriptor() ([]byte, []int) {
	return file_hub_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *Rejection) GetCode() RejectCode {
	if x != nil {
		return x.Code
	}
	return RejectCode_REJECT_CODE_UNSPECIFIED
}

func (x *Rejection) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Rejection) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_hub_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type HeartbeatResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Accepted                 bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	// 中台可要求插件重新注册（例如契约基线变更后）
	ReregisterRequired bool `protobuf:"varint,3,opt,name=reregister_required,json=reregisterRequired,proto3" json:"reregister_required,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_hub_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *HeartbeatResponse) GetReregisterRequired() bool {
	if x != nil {
		return x.ReregisterRequired
	}
	return false
}

type UnregisterRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Reason     string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// 注册时中台下发的状态凭证（`RegisterResponse.state_token`）。
	//
	// **注销要凭它认出「你是这一行的主人」。** `instance_id` 由插件自己生成，不同
	// 插件之间可以撞（缺省「主机名-PID」在同一 host 网络、容器 PID 又都是 1 时
	// 必然撞），而注销原本只按 `instance_id` 删行、不看属主——于是两个撞了 id 的
	// 插件里，谁先退出谁就把**对方**那一行删掉；对方的心跳仍按 instance_id 命中、
	// 返回 accepted，**完全察觉不到自己从注册表里消失了**（实测：auth 重启一次，
	// sql-executor 的工具从 MCP 工具面上全部消失，而它自己的日志停在「已注册到
	// 中台」之后再无输出）。
	//
	// 带上凭证之后这条路径自然消失：**没注册成功就没有凭证，也就注销不了**。
	// 这正是中台既有的立场——不信插件自报的身份，只信注册时下发的凭证
	// （HubState 的认证同此，见 `hub_store::instances::plugin_of_state_token`）。
	//
	// 留空（旧版插件）一律拒绝。代价只是优雅退出退化成「等心跳超时被摘除」
	// （`sweep_stale` 会兜住），而放行的代价是可能删掉别的插件的实例行。
	StateToken    string `protobuf:"bytes,3,opt,name=state_token,json=stateToken,proto3" json:"state_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_hub_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UnregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UnregisterRequest) GetStateToken() string {
	if x != nil {
		return x.StateToken
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_hub_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_registry_proto_rawDescGZIP(), []int{6}
}

var File_hub_v1_registry_proto protoreflect.FileDescriptor

const file_hub_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x15hub/v1/registry.proto\x12\x06hub.v1\x1a\x13hub/v1/plugin.proto\"\xef\x01\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0eadvertise_addr\x18\x04 \x01(\tR\radvertiseAddr\x122\n" +
	"\bmanifest\x18\x05 \x01(\v2\x16.hub.v1.PluginManifestR\bmanifest\x12%\n" +
	"\x0edescriptor_set\x18\x06 \x01(\fR\rdescriptorSet\"\xfd\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\x121\n" +
	"\n" +
	"rejections\x18\x04 \x03(\v2\x11.hub.v1.RejectionR\n" +
	"rejections\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x12\x1f\n" +
	"\vstate_token\x18\x06 \x01(\tR\n" +
	"stateToken\"e\n" +
	"\tRejection\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.hub.v1.RejectCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"3\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x9e\x01\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x02 \x01(\x05R\x18heartbeatIntervalSeconds\x12/\n" +
	"\x13reregister_required\x18\x03 \x01(\bR\x12reregisterRequired\"m\n" +
	"\x11UnregisterRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vstate_token\x18\x03 \x01(\tR\n" +
	"stateToken\"\x14\n" +
	"\x12UnregisterResponse*\xab\x02\n" +
	"\n" +
	"RejectCode\x12\x1b\n" +
	"\x17REJECT_CODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17REJECT_CODE_UNREACHABLE\x10\x01\x12\"\n" +
	"\x1eREJECT_CODE_DESCRIPTOR_INVALID\x10\x02\x12\x1f\n" +
	"\x1bREJECT_CODE_BREAKING_CHANGE\x10\x03\x12\x1d\n" +
	"\x19REJECT_CODE_TOOL_CONFLICT\x10\x04\x12 \n" +
	"\x1cREJECT_CODE_VERSION_CONFLICT\x10\x05\x12 \n" +
	"\x1cREJECT_CODE_MANIFEST_INVALID\x10\x06\x12\x18\n" +
	"\x14REJECT_CODE_INTERNAL\x10\a\x12!\n" +
	"\x1dREJECT_CODE_INSTANCE_CONFLICT\x10\b2\xd6\x01\n" +
	"\x0ePluginRegistry\x12=\n" +
	"\bRegister\x12\x17.hub.v1.RegisterRequest\x1a\x18.hub.v1.RegisterResponse\x12@\n" +
	"\tHeartbeat\x12\x18.hub.v1.HeartbeatRequest\x1a\x19.hub.v1.HeartbeatResponse\x12C\n" +
	"\n" +
	"Unregister\x12\x19.hub.v1.UnregisterRequest\x1a\x1a.hub.v1.UnregisterResponseBIZGgithub.com/mahingbun-dev/anc-hub/sdk/go/proto/hubv1;hubv1b\x06proto3"

var (
	file_hub_v1_registry_proto_rawDescOnce sync.Once
	file_hub_v1_registry_proto_rawDescData []byte
)

func file_hub_v1_registry_proto_rawDescGZIP() []byte {
	file_hub_v1_registry_proto_rawDescOnce.Do(func() {
		file_hub_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_v1_registry_proto_rawDesc), len(file_hub_v1_registry_proto_rawDesc)))
	})
	return file_hub_v1_registry_proto_rawDescData
}

var file_hub_v1_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hub_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hub_v1_registry_proto_goTypes = []any{
	(RejectCode)(0),            // 0: hub.v1.RejectCode
	(*RegisterRequest)(nil),    // 1: hub.v1.RegisterRequest
	(*RegisterResponse)(nil),   // 2: hub.v1.RegisterResponse
	(*Rejection)(nil),          // 3: hub.v1.Rejection
	(*HeartbeatRequest)(nil),   // 4: hub.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 5: hub.v1.HeartbeatResponse
	(*UnregisterRequest)(nil),  // 6: hub.v1.UnregisterRequest
	(*UnregisterResponse)(nil), // 7: hub.v1.UnregisterResponse
	(*PluginManifest)(nil),     // 8: hub.v1.PluginManifest
}
var file_hub_v1_registry_proto_depIdxs = []int32{
	8, // 0: hub.v1.RegisterRequest.manifest:type_name -> hub.v1.PluginManifest
	3, // 1: hub.v1.RegisterResponse.rejections:type_name -> hub.v1.Rejection
	0, // 2: hub.v1.Rejection.code:type_name -> hub.v1.RejectCode
	1, // 3: hub.v1.PluginRegistry.Register:input_type -> hub.v1.RegisterRequest
	4, // 4: hub.v1.PluginRegistry.Heartbeat:input_type -> hub.v1.HeartbeatRequest
	6, // 5: hub.v1.PluginRegistry.Unregister:input_type -> hub.v1.UnregisterRequest
	2, // 6: hub.v1.PluginRegistry.Register:output_type -> hub.v1.RegisterResponse
	5, // 7: hub.v1.PluginRegistry.Heartbeat:output_type -> hub.v1.HeartbeatResponse
	7, // 8: hub.v1.PluginRegistry.Unregister:output_type -> hub.v1.UnregisterResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hub_v1_registry_proto_init() }
func file_hub_v1_registry_proto_init() {
	if File_hub_v1_registry_proto != nil {
		return
	}
	file_hub_v1_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_v1_registry_proto_rawDesc), len(file_hub_v1_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_v1_registry_proto_goTypes,
		DependencyIndexes: file_hub_v1_registry_proto_depIdxs,
		EnumInfos:         file_hub_v1_registry_proto_enumTypes,
		MessageInfos:      file_hub_v1_registry_proto_msgTypes,
	}.Build()
	File_hub_v1_registry_proto = out.File
	file_hub_v1_registry_proto_goTypes = nil
	file_hub_v1_registry_proto_depIdxs = nil
}
