// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: hub/v1/registry.proto

package hubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginRegistry_Register_FullMethodName   = "/hub.v1.PluginRegistry/Register"
	PluginRegistry_Heartbeat_FullMethodName  = "/hub.v1.PluginRegistry/Heartbeat"
	PluginRegistry_Unregister_FullMethodName = "/hub.v1.PluginRegistry/Unregister"
)

// PluginRegistryClient is the client API for PluginRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 插件 → 中台。
//
// 插件是独立的进程/容器，可能部署在任何主机上，因此这条链路要经 nginx 的
// grpc_pass 独立端口进来（见 docs/design.md 的网络拓扑）。
//
// 心跳刻意用定时 unary 而非长连接 stream：避开 gRPC 经 nginx 的保活与超时坑。
type PluginRegistryClient interface {
	// 自注册。中台收到后会做三件事，任一不通过即拒绝：
	//   1. 可达性探测（试连 advertise_addr 并调 Health）
	//   2. descriptor 解析与字段级兼容检查
	//   3. MCP 工具名冲突检测
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// 优雅退出时主动摘除；未调用则由心跳超时兜底。
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
}

type pluginRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginRegistryClient(cc grpc.ClientConnInterface) PluginRegistryClient {
	return &pluginRegistryClient{cc}
}

func (c *pluginRegistryClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, PluginRegistry_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRegistryClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, PluginRegistry_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRegistryClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, PluginRegistry_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginRegistryServer is the server API for PluginRegistry service.
// All implementations should embed UnimplementedPluginRegistryServer
// for forward compatibility.
//
// 插件 → 中台。
//
// 插件是独立的进程/容器，可能部署在任何主机上，因此这条链路要经 nginx 的
// grpc_pass 独立端口进来（见 docs/design.md 的网络拓扑）。
//
// 心跳刻意用定时 unary 而非长连接 stream：避开 gRPC 经 nginx 的保活与超时坑。
type PluginRegistryServer interface {
	// 自注册。中台收到后会做三件事，任一不通过即拒绝：
	//   1. 可达性探测（试连 advertise_addr 并调 Health）
	//   2. descriptor 解析与字段级兼容检查
	//   3. MCP 工具名冲突检测
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// 优雅退出时主动摘除；未调用则由心跳超时兜底。
	Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
}

// UnimplementedPluginRegistryServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginRegistryServer struct{}

func (UnimplementedPluginRegistryServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPluginRegistryServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPluginRegistryServer) Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedPluginRegistryServer) testEmbeddedByValue() {}

// UnsafePluginRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginRegistryServer will
// result in compilation errors.
type UnsafePluginRegistryServer interface {
	mustEmbedUnimplementedPluginRegistryServer()
}

func RegisterPluginRegistryServer(s grpc.ServiceRegistrar, srv PluginRegistryServer) {
	// If the following call panics, it indicates UnimplementedPluginRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginRegistry_ServiceDesc, srv)
}

func _PluginRegistry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRegistry_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRegistryServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRegistry_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRegistryServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRegistry_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRegistryServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRegistry_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRegistryServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRegistry_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRegistryServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginRegistry_ServiceDesc is the grpc.ServiceDesc for PluginRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.v1.PluginRegistry",
	HandlerType: (*PluginRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PluginRegistry_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _PluginRegistry_Heartbeat_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _PluginRegistry_Unregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub/v1/registry.proto",
}
