// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: hub/v1/state.proto

package hubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KvKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 命名空间。中台会强制加上插件前缀（租户维度本期未实现，见文件头注释），
	// 插件填自己的业务子空间即可。
	//
	// **只允许 [A-Za-z0-9_.-]，非空，最长 200 字节**。放行 `*` 是漏洞不是功能：
	// 前缀靠字符串拼接，通配符会让 KvScan 变成跨命名空间的模式匹配。冒号同理。
	// 规则的事实来源是 sdk/go/hubkit/testdata/hub-rules.json，Rust 与 Go 两侧的
	// 实现由契约测试钉住（crates/hub-grpc/tests/state_rules.rs 与
	// sdk/go/hubkit/rules_test.go 读的是同一份文件）。
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// 键名。字符集与长度约束同 namespace。
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvKey) Reset() {
	*x = KvKey{}
	mi := &file_hub_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvKey) ProtoMessage() {}

func (x *KvKey) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvKey.ProtoReflect.Descriptor instead.
func (*KvKey) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *KvKey) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KvKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KvGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *KvKey                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvGetRequest) Reset() {
	*x = KvGetRequest{}
	mi := &file_hub_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvGetRequest) ProtoMessage() {}

func (x *KvGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvGetRequest.ProtoReflect.Descriptor instead.
func (*KvGetRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *KvGetRequest) GetKey() *KvKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type KvGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvGetResponse) Reset() {
	*x = KvGetResponse{}
	mi := &file_hub_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvGetResponse) ProtoMessage() {}

func (x *KvGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvGetResponse.ProtoReflect.Descriptor instead.
func (*KvGetResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *KvGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *KvGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KvPutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   *KvKey                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// 0 表示不过期
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvPutRequest) Reset() {
	*x = KvPutRequest{}
	mi := &file_hub_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvPutRequest) ProtoMessage() {}

func (x *KvPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvPutRequest.ProtoReflect.Descriptor instead.
func (*KvPutRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *KvPutRequest) GetKey() *KvKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KvPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KvPutRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type KvPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvPutResponse) Reset() {
	*x = KvPutResponse{}
	mi := &file_hub_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvPutResponse) ProtoMessage() {}

func (x *KvPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvPutResponse.ProtoReflect.Descriptor instead.
func (*KvPutResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{4}
}

type KvDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *KvKey                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvDeleteRequest) Reset() {
	*x = KvDeleteRequest{}
	mi := &file_hub_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvDeleteRequest) ProtoMessage() {}

func (x *KvDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvDeleteRequest.ProtoReflect.Descriptor instead.
func (*KvDeleteRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *KvDeleteRequest) GetKey() *KvKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type KvDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvDeleteResponse) Reset() {
	*x = KvDeleteResponse{}
	mi := &file_hub_v1_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvDeleteResponse) ProtoMessage() {}

func (x *KvDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvDeleteResponse.ProtoReflect.Descriptor instead.
func (*KvDeleteResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{6}
}

func (x *KvDeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type KvScanRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// 前缀。允许为空（表示扫整个命名空间）；非空时字符集同 namespace。
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// 上限，防止插件一次拉走整个命名空间
	Limit         uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvScanRequest) Reset() {
	*x = KvScanRequest{}
	mi := &file_hub_v1_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvScanRequest) ProtoMessage() {}

func (x *KvScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvScanRequest.ProtoReflect.Descriptor instead.
func (*KvScanRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{7}
}

func (x *KvScanRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KvScanRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *KvScanRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KvScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KvEntry             `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvScanResponse) Reset() {
	*x = KvScanResponse{}
	mi := &file_hub_v1_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvScanResponse) ProtoMessage() {}

func (x *KvScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvScanResponse.ProtoReflect.Descriptor instead.
func (*KvScanResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{8}
}

func (x *KvScanResponse) GetEntries() []*KvEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type KvEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvEntry) Reset() {
	*x = KvEntry{}
	mi := &file_hub_v1_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvEntry) ProtoMessage() {}

func (x *KvEntry) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvEntry.ProtoReflect.Descriptor instead.
func (*KvEntry) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{9}
}

func (x *KvEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标 flow 名或订阅 topic
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// 待投递的信封。其中 subject 由中台按调用方（插件）身份覆盖，
	// 插件不能借此外冒用他人身份。
	Envelope      *Envelope `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_hub_v1_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{10}
}

func (x *PublishRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PublishRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type PublishResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// 受理后产生的执行 id，供后续查链路
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// 被拒绝时的原因（例如检测到环）
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_hub_v1_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_state_proto_rawDescGZIP(), []int{11}
}

func (x *PublishResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PublishResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PublishResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_hub_v1_state_proto protoreflect.FileDescriptor

const file_hub_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x12hub/v1/state.proto\x12\x06hub.v1\x1a\x15hub/v1/envelope.proto\"7\n" +
	"\x05KvKey\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"/\n" +
	"\fKvGetRequest\x12\x1f\n" +
	"\x03key\x18\x01 \x01(\v2\r.hub.v1.KvKeyR\x03key\";\n" +
	"\rKvGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"f\n" +
	"\fKvPutRequest\x12\x1f\n" +
	"\x03key\x18\x01 \x01(\v2\r.hub.v1.KvKeyR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"\x0f\n" +
	"\rKvPutResponse\"2\n" +
	"\x0fKvDeleteRequest\x12\x1f\n" +
	"\x03key\x18\x01 \x01(\v2\r.hub.v1.KvKeyR\x03key\",\n" +
	"\x10KvDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"[\n" +
	"\rKvScanRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\";\n" +
	"\x0eKvScanResponse\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.hub.v1.KvEntryR\aentries\"1\n" +
	"\aKvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"V\n" +
	"\x0ePublishRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12,\n" +
	"\benvelope\x18\x02 \x01(\v2\x10.hub.v1.EnvelopeR\benvelope\"\\\n" +
	"\x0fPublishResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\xaa\x02\n" +
	"\bHubState\x124\n" +
	"\x05KvGet\x12\x14.hub.v1.KvGetRequest\x1a\x15.hub.v1.KvGetResponse\x124\n" +
	"\x05KvPut\x12\x14.hub.v1.KvPutRequest\x1a\x15.hub.v1.KvPutResponse\x12=\n" +
	"\bKvDelete\x12\x17.hub.v1.KvDeleteRequest\x1a\x18.hub.v1.KvDeleteResponse\x127\n" +
	"\x06KvScan\x12\x15.hub.v1.KvScanRequest\x1a\x16.hub.v1.KvScanResponse\x12:\n" +
	"\aPublish\x12\x16.hub.v1.PublishRequest\x1a\x17.hub.v1.PublishResponseBIZGgithub.com/mahingbun-dev/anc-hub/sdk/go/proto/hubv1;hubv1b\x06proto3"

var (
	file_hub_v1_state_proto_rawDescOnce sync.Once
	file_hub_v1_state_proto_rawDescData []byte
)

func file_hub_v1_state_proto_rawDescGZIP() []byte {
	file_hub_v1_state_proto_rawDescOnce.Do(func() {
		file_hub_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_v1_state_proto_rawDesc), len(file_hub_v1_state_proto_rawDesc)))
	})
	return file_hub_v1_state_proto_rawDescData
}

var file_hub_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_hub_v1_state_proto_goTypes = []any{
	(*KvKey)(nil),            // 0: hub.v1.KvKey
	(*KvGetRequest)(nil),     // 1: hub.v1.KvGetRequest
	(*KvGetResponse)(nil),    // 2: hub.v1.KvGetResponse
	(*KvPutRequest)(nil),     // 3: hub.v1.KvPutRequest
	(*KvPutResponse)(nil),    // 4: hub.v1.KvPutResponse
	(*KvDeleteRequest)(nil),  // 5: hub.v1.KvDeleteRequest
	(*KvDeleteResponse)(nil), // 6: hub.v1.KvDeleteResponse
	(*KvScanRequest)(nil),    // 7: hub.v1.KvScanRequest
	(*KvScanResponse)(nil),   // 8: hub.v1.KvScanResponse
	(*KvEntry)(nil),          // 9: hub.v1.KvEntry
	(*PublishRequest)(nil),   // 10: hub.v1.PublishRequest
	(*PublishResponse)(nil),  // 11: hub.v1.PublishResponse
	(*Envelope)(nil),         // 12: hub.v1.Envelope
}
var file_hub_v1_state_proto_depIdxs = []int32{
	0,  // 0: hub.v1.KvGetRequest.key:type_name -> hub.v1.KvKey
	0,  // 1: hub.v1.KvPutRequest.key:type_name -> hub.v1.KvKey
	0,  // 2: hub.v1.KvDeleteRequest.key:type_name -> hub.v1.KvKey
	9,  // 3: hub.v1.KvScanResponse.entries:type_name -> hub.v1.KvEntry
	12, // 4: hub.v1.PublishRequest.envelope:type_name -> hub.v1.Envelope
	1,  // 5: hub.v1.HubState.KvGet:input_type -> hub.v1.KvGetRequest
	3,  // 6: hub.v1.HubState.KvPut:input_type -> hub.v1.KvPutRequest
	5,  // 7: hub.v1.HubState.KvDelete:input_type -> hub.v1.KvDeleteRequest
	7,  // 8: hub.v1.HubState.KvScan:input_type -> hub.v1.KvScanRequest
	10, // 9: hub.v1.HubState.Publish:input_type -> hub.v1.PublishRequest
	2,  // 10: hub.v1.HubState.KvGet:output_type -> hub.v1.KvGetResponse
	4,  // 11: hub.v1.HubState.KvPut:output_type -> hub.v1.KvPutResponse
	6,  // 12: hub.v1.HubState.KvDelete:output_type -> hub.v1.KvDeleteResponse
	8,  // 13: hub.v1.HubState.KvScan:output_type -> hub.v1.KvScanResponse
	11, // 14: hub.v1.HubState.Publish:output_type -> hub.v1.PublishResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_hub_v1_state_proto_init() }
func file_hub_v1_state_proto_init() {
	if File_hub_v1_state_proto != nil {
		return
	}
	file_hub_v1_envelope_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_v1_state_proto_rawDesc), len(file_hub_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_v1_state_proto_goTypes,
		DependencyIndexes: file_hub_v1_state_proto_depIdxs,
		MessageInfos:      file_hub_v1_state_proto_msgTypes,
	}.Build()
	File_hub_v1_state_proto = out.File
	file_hub_v1_state_proto_goTypes = nil
	file_hub_v1_state_proto_depIdxs = nil
}
