// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: hub/v1/state.proto

package hubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubState_KvGet_FullMethodName    = "/hub.v1.HubState/KvGet"
	HubState_KvPut_FullMethodName    = "/hub.v1.HubState/KvPut"
	HubState_KvDelete_FullMethodName = "/hub.v1.HubState/KvDelete"
	HubState_KvScan_FullMethodName   = "/hub.v1.HubState/KvScan"
	HubState_Publish_FullMethodName  = "/hub.v1.HubState/Publish"
)

// HubStateClient is the client API for HubState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 插件 → 中台：外置状态 API。
//
// 插件被**强制无状态**——实例内存不保证跨调用保留，因此热切换零代价、
// 水平扩展无障碍、重放与测试都简单。所有需要跨调用保留的东西都走这里。
//
// 中台按**注册时下发的凭证**反查插件名并强制加前缀 `hub:state:{插件名}:`——前缀取自
// 凭证而非插件自报的字段，插件自报的 namespace 只作为子空间拼在后面。
//
// **但这不是插件间的隔离承诺**：凭证只证明注册方自称是某个插件名、并通过了该名字的
// 注册校验，不证明它就是那个插件。插件面按设计不鉴权，任何能连上该端口的进程都能注册
// 一个与目标插件契约兼容的新版本、拿到反查为该插件的凭证并读写它的状态空间。
// 隔离强度与完整边界见 `docs/design.md` 风险 11。
//
// **租户维度本期未实现**：HubState 请求只有 KvKey，没有 Envelope 上下文，
// 协议上推导不出"当前租户"，而插件自报的租户不可信。多租户需求出现时再单独设计。
type HubStateClient interface {
	KvGet(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error)
	KvPut(ctx context.Context, in *KvPutRequest, opts ...grpc.CallOption) (*KvPutResponse, error)
	KvDelete(ctx context.Context, in *KvDeleteRequest, opts ...grpc.CallOption) (*KvDeleteResponse, error)
	KvScan(ctx context.Context, in *KvScanRequest, opts ...grpc.CallOption) (*KvScanResponse, error)
	// 触发下游：把一条 Envelope 投给目标 flow。
	// 中台负责防环与限流，防止插件互相触发形成风暴。
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type hubStateClient struct {
	cc grpc.ClientConnInterface
}

func NewHubStateClient(cc grpc.ClientConnInterface) HubStateClient {
	return &hubStateClient{cc}
}

func (c *hubStateClient) KvGet(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvGetResponse)
	err := c.cc.Invoke(ctx, HubState_KvGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubStateClient) KvPut(ctx context.Context, in *KvPutRequest, opts ...grpc.CallOption) (*KvPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvPutResponse)
	err := c.cc.Invoke(ctx, HubState_KvPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubStateClient) KvDelete(ctx context.Context, in *KvDeleteRequest, opts ...grpc.CallOption) (*KvDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvDeleteResponse)
	err := c.cc.Invoke(ctx, HubState_KvDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubStateClient) KvScan(ctx context.Context, in *KvScanRequest, opts ...grpc.CallOption) (*KvScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvScanResponse)
	err := c.cc.Invoke(ctx, HubState_KvScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubStateClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, HubState_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubStateServer is the server API for HubState service.
// All implementations should embed UnimplementedHubStateServer
// for forward compatibility.
//
// 插件 → 中台：外置状态 API。
//
// 插件被**强制无状态**——实例内存不保证跨调用保留，因此热切换零代价、
// 水平扩展无障碍、重放与测试都简单。所有需要跨调用保留的东西都走这里。
//
// 中台按**注册时下发的凭证**反查插件名并强制加前缀 `hub:state:{插件名}:`——前缀取自
// 凭证而非插件自报的字段，插件自报的 namespace 只作为子空间拼在后面。
//
// **但这不是插件间的隔离承诺**：凭证只证明注册方自称是某个插件名、并通过了该名字的
// 注册校验，不证明它就是那个插件。插件面按设计不鉴权，任何能连上该端口的进程都能注册
// 一个与目标插件契约兼容的新版本、拿到反查为该插件的凭证并读写它的状态空间。
// 隔离强度与完整边界见 `docs/design.md` 风险 11。
//
// **租户维度本期未实现**：HubState 请求只有 KvKey，没有 Envelope 上下文，
// 协议上推导不出"当前租户"，而插件自报的租户不可信。多租户需求出现时再单独设计。
type HubStateServer interface {
	KvGet(context.Context, *KvGetRequest) (*KvGetResponse, error)
	KvPut(context.Context, *KvPutRequest) (*KvPutResponse, error)
	KvDelete(context.Context, *KvDeleteRequest) (*KvDeleteResponse, error)
	KvScan(context.Context, *KvScanRequest) (*KvScanResponse, error)
	// 触发下游：把一条 Envelope 投给目标 flow。
	// 中台负责防环与限流，防止插件互相触发形成风暴。
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
}

// UnimplementedHubStateServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubStateServer struct{}

func (UnimplementedHubStateServer) KvGet(context.Context, *KvGetRequest) (*KvGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvGet not implemented")
}
func (UnimplementedHubStateServer) KvPut(context.Context, *KvPutRequest) (*KvPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvPut not implemented")
}
func (UnimplementedHubStateServer) KvDelete(context.Context, *KvDeleteRequest) (*KvDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvDelete not implemented")
}
func (UnimplementedHubStateServer) KvScan(context.Context, *KvScanRequest) (*KvScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvScan not implemented")
}
func (UnimplementedHubStateServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedHubStateServer) testEmbeddedByValue() {}

// UnsafeHubStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubStateServer will
// result in compilation errors.
type UnsafeHubStateServer interface {
	mustEmbedUnimplementedHubStateServer()
}

func RegisterHubStateServer(s grpc.ServiceRegistrar, srv HubStateServer) {
	// If the following call panics, it indicates UnimplementedHubStateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubState_ServiceDesc, srv)
}

func _HubState_KvGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubStateServer).KvGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubState_KvGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubStateServer).KvGet(ctx, req.(*KvGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubState_KvPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubStateServer).KvPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubState_KvPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubStateServer).KvPut(ctx, req.(*KvPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubState_KvDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubStateServer).KvDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubState_KvDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubStateServer).KvDelete(ctx, req.(*KvDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubState_KvScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubStateServer).KvScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubState_KvScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubStateServer).KvScan(ctx, req.(*KvScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubState_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubStateServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubState_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubStateServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HubState_ServiceDesc is the grpc.ServiceDesc for HubState service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubState_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.v1.HubState",
	HandlerType: (*HubStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KvGet",
			Handler:    _HubState_KvGet_Handler,
		},
		{
			MethodName: "KvPut",
			Handler:    _HubState_KvPut_Handler,
		},
		{
			MethodName: "KvDelete",
			Handler:    _HubState_KvDelete_Handler,
		},
		{
			MethodName: "KvScan",
			Handler:    _HubState_KvScan_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _HubState_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub/v1/state.proto",
}
